class CfgPatches
{
	class Weapons_Globe_Explosives
	{
		addonRootClass="A3_Weapons_F_expEden";
		requiredAddons[]=
		{
			"A3_Weapons_F_expEden"
		};
		requiredVersion=0.1;
		units[]=
		{
			"FlareTripMine"
		};
		weapons[]=
		{
			"DroneDropMineDispenser_weapon",
			"DroneDropMineAT_weapon"
		};
	};
};
class CfgAmmo
{
	class mini_Grenade;
	class MissileBase;
	class SubmunitionBase;
	class ShotDeployBase;
	class ShellBase;
	class BombCore;
	class GrenadeHand;
	class F_20mm_Red;
	class APERSTripMine_Wire_Ammo;
	class FlareTripMine_Wire_Ammo: APERSTripMine_Wire_Ammo
	{
		model="\A3\Weapons_F\Explosives\Flare_tripwire.p3d";
		mineModelDisabled="\A3\Weapons_F\Explosives\Flare_tripwire_d.p3d";
		defaultMagazine="FlareTripMine_Wire_Mag";
		hit=1;
		indirectHit=0;
		indirectHitRange=1;
		suppressionRadiusHit=0;
		mineInconspicuousness=30;
		mineCanBeReactivated=0;
		minDamageForCamShakeHit=1.55;
		explosionEffects="CounterMeasureFlare";
		CraterEffects="";
		mineTrigger="WireTrigger";
		class CamShakeExplode
		{
			power=0;
			duration=0.2;
			frequency=20;
			distance=0;
		};
		class CamShakeHit
		{
			power=0;
			duration=0.2;
			frequency=20;
			distance=1;
		};
		soundTrigger[]=
		{
			"A3\Sounds_F_Orange\arsenal\explosives\Handling\ApersTripwire_Trigger_01",
			1.9,
			1,
			20
		};
		soundActivation[]=
		{
			"A3\Sounds_F_Orange\arsenal\explosives\Handling\ApersTripwire_Placement_01",
			1.7782794,
			1,
			20
		};
		soundDeactivation[]=
		{
			"A3\Sounds_F_Orange\arsenal\explosives\Handling\ApersTripwire_Deactivate_01",
			1.9952624,
			1,
			20
		};
		SoundSetExplosion[]=
		{
			"FlareTripMine_Exp_SoundSet",
			"FlareTripMine_Tail_SoundSet",
			"SMGSting_Tail_SoundSet"
		};
		class Eventhandlers
		{
			class Globe_FlareTripMine
			{
				AmmoHit="_this remoteExec ['expEden_fnc_activateFlareTripMine',2];";
			};
		};
	};
	class F_TripWireMine_Red: F_20mm_Red
	{
		lightColor[]={0.5,0.25,0.25};
		smokeColor[]={1,1,1,0.5};
		intensity=5000;
		affectedByWind=1;
		effectFlare="FlareShell";
		timeToLive=20;
		triggerTime=1.25;
	};
	class GrenadeHandATMine: GrenadeHand
	{
		hit=2000;
		indirectHit=2000;
		indirectHitRange=1;
		dangerRadiusHit=-1;
		suppressionRadiusHit=-1;
		typicalSpeed=3;
		deflecting=0.1;
		timeToLive=-1;
		explosionTime=4.0900002;
		model="\A3\Weapons_f\Explosives\mine_at";
		SoundSetExplosion[]=
		{
			"ATmine_Exp_SoundSet",
			"BigIED_Tail_SoundSet",
			"Explosion_Debris_SoundSet",
			"UXO_Debris_SoundSet",
			"UXO_Debris_Dust_Cloud_SoundSet"
		};
		CraterEffects="ATMineCrater";
		explosionEffects="ATMineExplosion_Globe";
		soundImpactSoft[]=
		{
			"a3\sounds_f\weapons\grenades\grenade_drop",
			1.4125376,
			1,
			60
		};
		soundImpactHard1[]=
		{
			"a3\sounds_f\vehicles\boat\noises\light_metal_boat_crash_building_01",
			1.4125376,
			1,
			65
		};
		soundImpactHard2[]=
		{
			"a3\sounds_f\vehicles\boat\noises\light_metal_boat_crash_building_02",
			1.4125376,
			1,
			65
		};
		soundImpactHard3[]=
		{
			"a3\sounds_f\vehicles\boat\noises\light_metal_boat_crash_building_03",
			1.4125376,
			1,
			65
		};
		soundImpactIron1[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_armor_1",
			1.2589254,
			1,
			95
		};
		soundImpactIron2[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_armor_2",
			1.2589254,
			1,
			95
		};
		soundImpactIron3[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_armor_3",
			1.2589254,
			1,
			95
		};
		soundImpactIron4[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_armor_4",
			1.2589254,
			1,
			95
		};
		soundImpactWoodExt1[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_wood_1",
			1.4125376,
			1,
			75
		};
		soundImpactWoodExt2[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_wood_2",
			1.4125376,
			1,
			75
		};
		soundImpactWoodExt3[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_wood_3",
			1.4125376,
			1,
			75
		};
		soundImpactWoodExt4[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_wood_4",
			1.4125376,
			1,
			75
		};
		impactGroundSoft[]=
		{
			"soundImpactSoft",
			1
		};
		impactGroundHard[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactIron[]=
		{
			"soundImpactIron1",
			0.25,
			"soundImpactIron2",
			0.25,
			"soundImpactIron3",
			0.25,
			"soundImpactIron4",
			0.25
		};
		impactArmor[]=
		{
			"soundImpactIron1",
			0.25,
			"soundImpactIron2",
			0.25,
			"soundImpactIron3",
			0.25,
			"soundImpactIron4",
			0.25
		};
		impactBuilding[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactFoliage[]=
		{
			"soundImpactSoft",
			1
		};
		impactWood[]=
		{
			"soundImpactWoodExt1",
			0.25,
			"soundImpactWoodExt2",
			0.25,
			"soundImpactWoodExt3",
			0.25,
			"soundImpactWoodExt4",
			0.25
		};
		impactGlass[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactGlassArmored[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactConcrete[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactTyre[]=
		{
			"soundImpactSoft",
			1
		};
		impactRubber[]=
		{
			"soundImpactSoft",
			1
		};
		impactPlastic[]=
		{
			"soundImpactSoft",
			1
		};
		impactDefault[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactMetal[]=
		{
			"soundImpactIron1",
			0.25,
			"soundImpactIron2",
			0.25,
			"soundImpactIron3",
			0.25,
			"soundImpactIron4",
			0.25
		};
		impactMetalplate[]=
		{
			"soundImpactIron1",
			0.25,
			"soundImpactIron2",
			0.25,
			"soundImpactIron3",
			0.25,
			"soundImpactIron4",
			0.25
		};
		soundImpactWater1[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_water_1",
			1,
			1,
			65
		};
		soundImpactWater2[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_water_2",
			1,
			1,
			65
		};
		soundImpactWater3[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_water_3",
			1,
			1,
			65
		};
		impactWater[]=
		{
			"soundImpactWater1",
			0.33333334,
			"soundImpactWater2",
			0.33333334,
			"soundImpactWater3",
			0.33333334
		};
		soundGlass1[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_01",
			1.7782794,
			1,
			100
		};
		soundGlass2[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_02",
			1.7782794,
			1,
			100
		};
		soundGlass3[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_03",
			1.7782794,
			1,
			100
		};
		soundGlass4[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_04",
			1.7782794,
			1,
			100
		};
		soundGlass5[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_05",
			1.7782794,
			1,
			100
		};
		soundGlass6[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_06",
			1.7782794,
			1,
			100
		};
		soundGlass7[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_07",
			1.7782794,
			1,
			100
		};
		soundGlass8[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_08",
			1.7782794,
			1,
			100
		};
		hitGlassBreak[]=
		{
			"soundGlass1",
			0.125,
			"soundGlass2",
			0.125,
			"soundGlass3",
			0.125,
			"soundGlass4",
			0.125,
			"soundGlass5",
			0.125,
			"soundGlass6",
			0.125,
			"soundGlass7",
			0.125,
			"soundGlass8",
			0.125
		};
		soundHitBody3[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\body_03",
			2.2387211,
			1,
			100
		};
		soundHitBody4[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\body_04",
			2.2387211,
			1,
			100
		};
		soundHitBody5[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\body_05",
			2.2387211,
			1,
			100
		};
		soundHitBody6[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\body_06",
			2.2387211,
			1,
			100
		};
		impactMan[]=
		{
			"soundHitBody3",
			0.25,
			"soundHitBody4",
			0.25,
			"soundHitBody5",
			0.25,
			"soundHitBody6",
			0.25
		};
		class CamShakeExplode
		{
			power=36;
			duration=1.5;
			frequency=21;
			distance=161.32599;
		};
		class CamShakeHit
		{
			power=200;
			duration=0.2;
			frequency=10;
			distance=1;
		};
	};
	class DroneDropMineAT_ammo: BombCore
	{
		simulation="shotMissile";
		hit=0;
		indirectHit=0;
		indirectHitRange=0;
		cost=500;
		irLock=0;
		laserLock=0;
		airFriction=0.079999998;
		sideAirFriction=0.12;
		maneuvrability=4.5999999;
		trackLead=0;
		maxSpeed=100;
		timeToLive=1;
		initTime=0;
		thrustTime=0;
		thrust=0;
		explosionSoundEffect="";
		model="\A3\Weapons_f\Explosives\mine_at";
		proxyShape="\a3\weapons_f\explosives\mine_at";
		CraterEffects="";
		explosionEffects="";
		whistleDist=24;
		triggerTime=0.1;
		triggerOnImpact=0;
		triggerSpeedCoef[]={1,1};
		submunitionConeAngle=0;
		submunitionDirectionType="SubmunitionModelDirection";
		submunitionParentSpeedCoef=1;
		submunitionConeType[]=
		{
			"custom",
			
			{
				{0,0}
			}
		};
		submunitionAmmo="DroneDropMineAT_ammoSub";
	};
	class DroneDropMineAT_ammoSub: ShellBase
	{
		simulation="shotGrenade";
		model="\A3\Weapons_f\Explosives\mine_at";
		hit=2000;
		indirectHit=2000;
		indirectHitRange=1;
		explosionTime=4.0900002;
		thrust=0;
		thrustTime=0;
		typicalSpeed=1;
		craterShape="\a3\Data_f_orange\data\krater_maly";
		effectsMissile="";
		explosionEffects="ATMineExplosion_Globe";
		CraterEffects="ATMineCrater";
		SoundSetExplosion[]=
		{
			"ATmine_Exp_SoundSet",
			"BigIED_Tail_SoundSet",
			"Explosion_Debris_SoundSet",
			"UXO_Debris_SoundSet",
			"UXO_Debris_Dust_Cloud_SoundSet"
		};
		soundImpactSoft[]=
		{
			"a3\sounds_f\weapons\grenades\grenade_drop",
			1.4125376,
			1,
			60
		};
		soundImpactHard1[]=
		{
			"a3\sounds_f\vehicles\boat\noises\light_metal_boat_crash_building_01",
			1.4125376,
			1,
			65
		};
		soundImpactHard2[]=
		{
			"a3\sounds_f\vehicles\boat\noises\light_metal_boat_crash_building_02",
			1.4125376,
			1,
			65
		};
		soundImpactHard3[]=
		{
			"a3\sounds_f\vehicles\boat\noises\light_metal_boat_crash_building_03",
			1.4125376,
			1,
			65
		};
		soundImpactIron1[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_armor_1",
			1.2589254,
			1,
			95
		};
		soundImpactIron2[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_armor_2",
			1.2589254,
			1,
			95
		};
		soundImpactIron3[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_armor_3",
			1.2589254,
			1,
			95
		};
		soundImpactIron4[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_armor_4",
			1.2589254,
			1,
			95
		};
		soundImpactWoodExt1[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_wood_1",
			1.4125376,
			1,
			75
		};
		soundImpactWoodExt2[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_wood_2",
			1.4125376,
			1,
			75
		};
		soundImpactWoodExt3[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_wood_3",
			1.4125376,
			1,
			75
		};
		soundImpactWoodExt4[]=
		{
			"a3\sounds_f\vehicles\crashes\cars\quadbike_coll_wood_4",
			1.4125376,
			1,
			75
		};
		impactGroundSoft[]=
		{
			"soundImpactSoft",
			1
		};
		impactGroundHard[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactIron[]=
		{
			"soundImpactIron1",
			0.25,
			"soundImpactIron2",
			0.25,
			"soundImpactIron3",
			0.25,
			"soundImpactIron4",
			0.25
		};
		impactArmor[]=
		{
			"soundImpactIron1",
			0.25,
			"soundImpactIron2",
			0.25,
			"soundImpactIron3",
			0.25,
			"soundImpactIron4",
			0.25
		};
		impactBuilding[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactFoliage[]=
		{
			"soundImpactSoft",
			1
		};
		impactWood[]=
		{
			"soundImpactWoodExt1",
			0.25,
			"soundImpactWoodExt2",
			0.25,
			"soundImpactWoodExt3",
			0.25,
			"soundImpactWoodExt4",
			0.25
		};
		impactGlass[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactGlassArmored[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactConcrete[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactTyre[]=
		{
			"soundImpactSoft",
			1
		};
		impactRubber[]=
		{
			"soundImpactSoft",
			1
		};
		impactPlastic[]=
		{
			"soundImpactSoft",
			1
		};
		impactDefault[]=
		{
			"soundImpactHard1",
			0.33333299,
			"soundImpactHard2",
			0.33333299,
			"soundImpactHard3",
			0.33333299
		};
		impactMetal[]=
		{
			"soundImpactIron1",
			0.25,
			"soundImpactIron2",
			0.25,
			"soundImpactIron3",
			0.25,
			"soundImpactIron4",
			0.25
		};
		impactMetalplate[]=
		{
			"soundImpactIron1",
			0.25,
			"soundImpactIron2",
			0.25,
			"soundImpactIron3",
			0.25,
			"soundImpactIron4",
			0.25
		};
		soundImpactWater1[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_water_1",
			1,
			1,
			65
		};
		soundImpactWater2[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_water_2",
			1,
			1,
			65
		};
		soundImpactWater3[]=
		{
			"A3\Sounds_F\weapons\Grenades\handgrenade_drops\handg_drop_water_3",
			1,
			1,
			65
		};
		impactWater[]=
		{
			"soundImpactWater1",
			0.33333334,
			"soundImpactWater2",
			0.33333334,
			"soundImpactWater3",
			0.33333334
		};
		soundGlass1[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_01",
			1.7782794,
			1,
			100
		};
		soundGlass2[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_02",
			1.7782794,
			1,
			100
		};
		soundGlass3[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_03",
			1.7782794,
			1,
			100
		};
		soundGlass4[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_04",
			1.7782794,
			1,
			100
		};
		soundGlass5[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_05",
			1.7782794,
			1,
			100
		};
		soundGlass6[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_06",
			1.7782794,
			1,
			100
		};
		soundGlass7[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_07",
			1.7782794,
			1,
			100
		};
		soundGlass8[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\glass_08",
			1.7782794,
			1,
			100
		};
		hitGlassBreak[]=
		{
			"soundGlass1",
			0.125,
			"soundGlass2",
			0.125,
			"soundGlass3",
			0.125,
			"soundGlass4",
			0.125,
			"soundGlass5",
			0.125,
			"soundGlass6",
			0.125,
			"soundGlass7",
			0.125,
			"soundGlass8",
			0.125
		};
		soundHitBody3[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\body_03",
			2.2387211,
			1,
			100
		};
		soundHitBody4[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\body_04",
			2.2387211,
			1,
			100
		};
		soundHitBody5[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\body_05",
			2.2387211,
			1,
			100
		};
		soundHitBody6[]=
		{
			"A3\Sounds_F\arsenal\sfx\bullet_hits\body_06",
			2.2387211,
			1,
			100
		};
		impactMan[]=
		{
			"soundHitBody3",
			0.25,
			"soundHitBody4",
			0.25,
			"soundHitBody5",
			0.25,
			"soundHitBody6",
			0.25
		};
		soundFall[]=
		{
			"",
			1,
			1
		};
		soundFakeFall[]=
		{
			"soundFall",
			1
		};
		class CamShakeExplode
		{
			power=36;
			duration=1.5;
			frequency=21;
			distance=161.32599;
		};
		class CamShakeHit
		{
			power=200;
			duration=0.2;
			frequency=10;
			distance=1;
		};
	};
	class DroneDropMineDispenserAT_ammo: BombCore
	{
		simulation="shotMissile";
		simulationStep=0.050000001;
		model="\A3\Weapons_f\Explosives\mine_at";
		hit=0;
		indirectHit=0;
		indirectHitRange=8;
		cost=1000;
		irLock=0;
		laserLock=0;
		airFriction=0.079999998;
		sideAirFriction=0.12;
		maneuvrability=4.5999999;
		trackLead=0;
		artilleryLock=0;
		maxSpeed=100;
		hitOnWater=1;
		visibleFire=16;
		visibleFireTime=10;
		audibleFire=16;
		deflecting=5;
		timeToLive=2;
		initTime=0;
		thrustTime=0;
		thrust=0;
		explosionSoundEffect="";
		proxyShape="";
		CraterEffects="";
		explosionEffects="";
		whistleDist=24;
		triggerTime=0.2;
		triggerOnImpact=1;
		submunitionConeAngle=15;
		submunitionConeType[]=
		{
			"randomcenter",
			1
		};
		triggerSpeedCoef=0.25;
		submunitionAmmo="DroneDropMineDispenserAT_ammoSub";
	};
	class DroneDropMineDispenserAT_ammoSub: ShotDeployBase
	{
		submunitionAmmo="ATMine_Range_Ammo";
		airFriction=1;
		EffectFly="";
		hit=300;
		model="\A3\Weapons_f\Explosives\mine_at";
		mineFloating=1000;
	};
	class DroneDropMineDispenserAPERS_ammo: BombCore
	{
		simulation="shotMissile";
		simulationStep=0.050000001;
		model="\A3\Weapons_F\explosives\mine_ap_i";
		hit=0;
		indirectHit=0;
		indirectHitRange=8;
		cost=1000;
		irLock=0;
		laserLock=0;
		airFriction=0.079999998;
		sideAirFriction=0.12;
		maneuvrability=4.5999999;
		trackLead=0;
		artilleryLock=0;
		maxSpeed=100;
		hitOnWater=1;
		visibleFire=16;
		visibleFireTime=10;
		audibleFire=16;
		deflecting=5;
		timeToLive=2;
		initTime=0;
		thrustTime=0;
		thrust=0;
		explosionSoundEffect="";
		proxyShape="";
		CraterEffects="";
		explosionEffects="";
		whistleDist=24;
		triggerTime=0.2;
		triggerOnImpact=1;
		submunitionConeAngle=19;
		submunitionConeType[]=
		{
			"random",
			4
		};
		submunitionAmmo="DroneDropMineDispenserAPERS_ammoSub";
	};
	class DroneDropMineDispenserAPERS_ammoSub: ShotDeployBase
	{
		submunitionAmmo="APERSMine_Range_Ammo";
		airFriction=1;
		EffectFly="";
		hit=300;
		model="\A3\Weapons_F\explosives\mine_ap_i";
		mineFloating=1000;
	};
	class DroneDropMineDispenserAPERSmd_ammo: BombCore
	{
		simulation="shotMissile";
		simulationStep=0.050000001;
		model="\A3\Weapons_F_Orange\Explosives\APERSmineDispenser_AP";
		hit=0;
		indirectHit=0;
		indirectHitRange=8;
		cost=1000;
		irLock=0;
		laserLock=0;
		airFriction=0.079999998;
		sideAirFriction=0.12;
		maneuvrability=4.5999999;
		trackLead=0;
		artilleryLock=0;
		maxSpeed=100;
		hitOnWater=1;
		visibleFire=16;
		visibleFireTime=10;
		audibleFire=16;
		deflecting=5;
		timeToLive=2;
		initTime=0;
		thrustTime=0;
		thrust=0;
		explosionSoundEffect="";
		proxyShape="";
		CraterEffects="";
		explosionEffects="";
		whistleDist=24;
		triggerTime=0.2;
		triggerOnImpact=1;
		submunitionConeAngle=21;
		submunitionConeType[]=
		{
			"random",
			5
		};
		submunitionAmmo="DroneDropMineDispenserAPERSmd_ammoSub";
	};
	class DroneDropMineDispenserAPERSmd_ammoSub: ShotDeployBase
	{
		submunitionAmmo="APERSMineDispenser_Mine_Ammo";
		airFriction=1;
		EffectFly="";
		hit=300;
		model="\A3\Weapons_F_Orange\Explosives\APERSmineDispenser_AP";
		mineFloating=1000;
	};
	class Sh_82mm_AMOS_airburst_ammo: SubmunitionBase
	{
		submunitionAmmo="Sh_82mm_AMOS_airburst_ammoSub";
		submunitionCount=1;
		submunitionConeAngle=0;
		laserLock=0;
		autoSeekTarget=1;
		cost=200;
		muzzleEffect="";
		fuseDistance=150;
		triggerDistance=10;
		airFriction=0;
		hit=0;
	};
	class Sh_82mm_AMOS_airburst_ammoSub: MissileBase
	{
		timeToLive=0.25;
		model="\A3\weapons_f\ammo\shell";
		hit=165;
		indirectHit=52;
		indirectHitRange=18;
		cost=200;
		muzzleEffect="";
		dangerRadiusHit=750;
		suppressionRadiusHit=75;
		class CamShakeExplode
		{
			power=16.4;
			duration=1.8;
			frequency=20;
			distance=216.44299;
		};
		class CamShakeHit
		{
			power=82;
			duration=0.60000002;
			frequency=20;
			distance=1;
		};
		class CamShakeFire
		{
			power=3.0092199;
			duration=1.8;
			frequency=20;
			distance=72.4431;
		};
		class CamShakePlayerFire
		{
			power=0.0099999998;
			duration=0.1;
			frequency=20;
			distance=1;
		};
		SoundSetExplosion[]=
		{
			"Mortar_Exp_SoundSet",
			"Mortar_Tail_SoundSet"
		};
		autoSeekTarget=0;
		airLock=0;
		maneuvrability=6;
		simulationStep=0.0020000001;
		fuseDistance=0;
		airFriction=0.0099999998;
		sideAirFriction=0.029999999;
	};
	class GrenadeHandSabotaged_01_G: GrenadeHand
	{
		hit=2.5;
		indirectHit=4;
		indirectHitRange=3;
		model="\A3\Weapons_f\ammo\Handgrenade";
		explosionTime=0.15;
		class EventHandlers
		{
			class Globe_fuzePop
			{
				fired="playSound3D ['\a3\sounds_f\weapons\mines\expl_trigger_1.wss', (_this # 0), false, getPosASL (_this # 0), 1, 1, 40, 0, true]";
			};
		};
	};
	class mini_GrenadeSabotaged_01_G: mini_Grenade
	{
		hit=1.3;
		indirectHit=3;
		indirectHitRange=2;
		model="\A3\Weapons_f\ammo\mini_frag";
		explosionTime=0.15;
	};
	class explosive_UAVLM_01_G: BombCore
	{
		hit=2500;
		indirectHit=550;
		indirectHitRange=12;
		dangerRadiusHit=1250;
		suppressionRadiusHit=100;
		cost=400;
		irLock=0;
		laserLock=0;
		airFriction=0.079999998;
		sideAirFriction=0.12;
		maneuvrability=4.5999999;
		trackLead=0;
		maxSpeed=100;
		timeToLive=120;
		initTime=0;
		thrustTime=0;
		thrust=0;
		soundHit1[]=
		{
			"A3\Sounds_F\weapons\Explosion\expl_big_1",
			2.5118864,
			1,
			1500
		};
		soundHit2[]=
		{
			"A3\Sounds_F\weapons\Explosion\expl_big_2",
			2.5118864,
			1,
			1500
		};
		soundHit3[]=
		{
			"A3\Sounds_F\weapons\Explosion\expl_big_3",
			2.5118864,
			1,
			1500
		};
		soundHit4[]=
		{
			"A3\Sounds_F\weapons\Explosion\expl_shell_1",
			2.5118864,
			1,
			1500
		};
		soundHit5[]=
		{
			"A3\Sounds_F\weapons\Explosion\expl_shell_2",
			2.5118864,
			1,
			1500
		};
		multiSoundHit[]=
		{
			"soundHit1",
			0.2,
			"soundHit2",
			0.2,
			"soundHit3",
			0.2,
			"soundHit4",
			0.2,
			"soundHit5",
			0.2
		};
		explosionSoundEffect="DefaultExplosion";
		model="";
		proxyShape="";
		CraterEffects="BombCrater";
		explosionEffects="UAVLM_Explosion_01";
		whistleDist=24;
		SoundSetExplosion[]=
		{
			"UAVLM_Exp_SoundSet",
			"UAVLM_Tail_SoundSet",
			"Explosion_Debris_SoundSet"
		};
	};
	class explosive_UAVLM_02_G: explosive_UAVLM_01_G
	{
		CraterEffects="";
		explosionEffects="UAVLM_Explosion_02";
	};
};
class CfgMagazines
{
	class CA_Magazine;
	class VehicleMagazine;
	class HandGrenade;
	class MiniGrenade;
	class HandGrenadeSabotaged_01_G: HandGrenade
	{
		author="O&T Expansion Eden";
		scope=1;
		mass=9.55;
		ammo="GrenadeHandSabotaged_01_G";
	};
	class MiniGrenadeSabotaged_01_G: MiniGrenade
	{
		author="O&T Expansion Eden";
		mass=5.55;
		scope=1;
		ammo="mini_GrenadeSabotaged_01_G";
	};
	class APERSTripMine_Wire_Mag;
	class FlareTripMine_Wire_Mag: APERSTripMine_Wire_Mag
	{
		author="O&T Expansion Eden";
		ammo="FlareTripMine_Wire_Ammo";
		displayName="$STR_Globe_CfgMagazines_FlareTripMine_Wire_Mag0";
		displayNameShort="$STR_Globe_CfgMagazines_FlareTripMine_Wire_Mag0";
		picture="\A3\Weapons_F\Data\UI\gear_flare_tripwire_ca.paa";
		model="\A3\Weapons_F\Explosives\Flare_tripwire_i.p3d";
		descriptionShort="$STR_Globe_CfgMagazines_FlareTripMine_Wire_Mag1";
		class Library
		{
			libTextDesc="$STR_Globe_CfgMagazines_FlareTripMine_Wire_Library0";
		};
	};
	class HandGrenadeATMine: HandGrenade
	{
		author="O&T Expansion Eden";
		mass=80;
		initSpeed=5;
		picture="\A3\Weapons_F_expEden\Explosives\Data\UI\gear_mineThrowable_at_ca.paa";
		model="\A3\Weapons_f\Explosives\mine_at";
		ammo="GrenadeHandATMine";
		displayName="$STR_Globe_CfgMagazines_HandGrenadeATMine_dn";
		displayNameShort="$STR_Globe_CfgMagazines_HandGrenadeATMine_dns";
		descriptionShort="$STR_Globe_CfgMagazines_HandGrenadeATMine_ds";
	};
	class DroneDropMineAT_magazine: VehicleMagazine
	{
		author="O&T Expansion Eden";
		scope=2;
		ammo="DroneDropMineAT_ammo";
		displayName="$STR_a3_cfgmagazines_mine0";
		descriptionShort="ds m";
		displayNameShort="$STR_Globe_CfgVehicles_UAV_01_DroneDropMineAT_base1";
		initSpeed=0;
		maxLeadSpeed=25;
		count=1;
		nameSound="missiles";
		model="\A3\Weapons_f\Explosives\mine_at";
		hardpoints[]=
		{
			"DRONE_DROP_MINE_AT"
		};
		pylonWeapon="DroneDropMineAT_weapon";
		mass=80;
		weight=80;
	};
	class DroneDropMineDispenserAT_magazine: VehicleMagazine
	{
		author="O&T Expansion Eden";
		scope=2;
		ammo="DroneDropMineDispenserAT_ammo";
		displayName="$STR_a3_cfgmagazines_mine0";
		descriptionShort="ds m";
		displayNameShort="$STR_Globe_1_pcs0";
		initSpeed=0;
		maxLeadSpeed=25;
		count=1;
		nameSound="missiles";
		model="\A3\Weapons_f\Explosives\mine_at";
		hardpoints[]=
		{
			"DRONE_DROP_MINE_DISPENSER"
		};
		pylonWeapon="DroneDropMineDispenser_weapon";
		mass=80;
		weight=80;
	};
	class DroneDropMineDispenserAPERS_magazine: VehicleMagazine
	{
		author="O&T Expansion Eden";
		scope=2;
		ammo="DroneDropMineDispenserAPERS_ammo";
		displayName="$STR_a3_cfgmagazines_classicminerangemagazine0";
		descriptionShort="ds m";
		displayNameShort="$STR_Globe_4_pcs0";
		initSpeed=0;
		maxLeadSpeed=25;
		count=1;
		nameSound="missiles";
		model="\A3\Weapons_F\explosives\mine_ap_i";
		hardpoints[]=
		{
			"DRONE_DROP_MINE_DISPENSER"
		};
		pylonWeapon="DroneDropMineDispenser_weapon";
		mass=40;
		weight=40;
	};
	class DroneDropMineDispenserAPERSmd_magazine: VehicleMagazine
	{
		author="O&T Expansion Eden";
		scope=2;
		ammo="DroneDropMineDispenserAPERSmd_ammo";
		displayName="$STR_Globe_Cfgmagazines_DroneDropMineDispenserAPERSmd_magazine0";
		descriptionShort="$STR_a3_cfgvehicles_apersminedispenser_mine_f0";
		displayNameShort="$STR_Globe_5_pcs0";
		initSpeed=0;
		maxLeadSpeed=25;
		count=1;
		nameSound="missiles";
		model="\A3\Weapons_F_Orange\Explosives\APERSmineDispenser_AP";
		hardpoints[]=
		{
			"DRONE_DROP_MINE_DISPENSER"
		};
		pylonWeapon="DroneDropMineDispenser_weapon";
		mass=37;
		weight=37;
	};
	class Sh_82mm_AMOS_airburst_magazine: VehicleMagazine
	{
		author="O&T Expansion Eden";
		initSpeed=810;
		displayNameShort="$STR_A3_CfgMagazines_50Rnd_120mm_Mo_shells_dns";
		scope=2;
		displayName="$STR_A3_CfgMagazines_50Rnd_120mm_Mo_shells0";
		displayNameMFDFormat="HE";
		ammo="Sh_82mm_AMOS_airburst_ammo";
		count=2;
		nameSound="heat";
		muzzleImpulseFactor[]={0.1,2};
	};	
};
class CfgWeapons
{
	class CannonCore;
	class Mk82BombLauncher;
	class GrenadeLauncher;
	class Default;
	class Put: Default
	{
		class PutMuzzle;
		class FlareTripMineMuzzle: PutMuzzle
		{
			displayName="$STR_Globe_CfgWeapons_FlareTripMineMuzzle0";
			magazines[]=
			{
				"FlareTripMine_Wire_Mag"
			};
			showToPlayer=0;
			enableAttack=1;
			autoreload=0;
		};
		muzzles[]+=
		{
			"FlareTripMineMuzzle"
		};
	};
	class Throw: GrenadeLauncher
	{
		class ThrowMuzzle;
		muzzles[]+=
		{
			"HandGrenadeATMineMuzzle"
		};
		class HandGrenadeATMineMuzzle: ThrowMuzzle
		{
			magazines[]=
			{
				"HandGrenadeATMine"
			};
		};
		class HandGrenadeMuzzle: ThrowMuzzle
		{
			magazines[]+=
			{
				"HandGrenadeSabotaged_01_G"
			};
		};
		class MiniGrenadeMuzzle: ThrowMuzzle
		{
			magazines[]+=
			{
				"MiniGrenadeSabotaged_01_G"
			};
		};
	};
	class DroneDropMineAT_weapon: Mk82BombLauncher
	{
		displayName="$STR_a3_cfgmagazines_mine0";
		scope=2;
		magazines[]=
		{
			"DroneDropMineAT_magazine"
		};
		model="\A3\Weapons_f\Explosives\mine_at.p3d";
		autoFire=0;
		reloadTime=0;
		initSpeed=0;
		maxLeadSpeed=25;
		cursorAim="";
		sounds[]=
		{
			"Bomb_Demine_Release"
		};
		class Bomb_Demine_Release
		{
			Bomb_Demine_Release_01[]=
			{
				"A3\Sounds_F_Orange\Vehicles\Air\UAV_06\UAV_6_DemineDrone_Bomb_Release_01",
				3.9810717,
				1,
				20
			};
			Bomb_Demine_Release_02[]=
			{
				"A3\Sounds_F_Orange\Vehicles\Air\UAV_06\UAV_6_DemineDrone_Bomb_Release_02",
				3.9810717,
				1,
				20
			};
			Bomb_Demine_Release_03[]=
			{
				"A3\Sounds_F_Orange\Vehicles\Air\UAV_06\UAV_6_DemineDrone_Bomb_Release_03",
				3.9810717,
				1,
				20
			};
			Bomb_Demine_Release_04[]=
			{
				"A3\Sounds_F_Orange\Vehicles\Air\UAV_06\UAV_6_DemineDrone_Bomb_Release_04",
				3.9810717,
				1,
				20
			};
			soundBegin[]=
			{
				"Bomb_Demine_Release_01",
				0.25,
				"Bomb_Demine_Release_02",
				0.25,
				"Bomb_Demine_Release_03",
				0.25,
				"Bomb_Demine_Release_04",
				0.25
			};
		};
	};
	class DroneDropMineDispenser_weapon: Mk82BombLauncher
	{
		displayName="$STR_a3_orange_cfghints_minedispensers_displayname";
		scope=2;
		magazines[]=
		{
			"DroneDropMineDispenserAPERSmd_magazine",
			"DroneDropMineDispenserAT_magazine",
			"DroneDropMineDispenserAPERS_magazine"
		};
		autoFire=0;
		reloadTime=0;
		initSpeed=0;
		maxLeadSpeed=25;
		cursorAim="";
		sounds[]=
		{
			"Bomb_Demine_Release"
		};
		class Bomb_Demine_Release
		{
			Bomb_Demine_Release_01[]=
			{
				"A3\Sounds_F_Orange\Vehicles\Air\UAV_06\UAV_6_DemineDrone_Bomb_Release_01",
				3.9810717,
				1,
				20
			};
			Bomb_Demine_Release_02[]=
			{
				"A3\Sounds_F_Orange\Vehicles\Air\UAV_06\UAV_6_DemineDrone_Bomb_Release_02",
				3.9810717,
				1,
				20
			};
			Bomb_Demine_Release_03[]=
			{
				"A3\Sounds_F_Orange\Vehicles\Air\UAV_06\UAV_6_DemineDrone_Bomb_Release_03",
				3.9810717,
				1,
				20
			};
			Bomb_Demine_Release_04[]=
			{
				"A3\Sounds_F_Orange\Vehicles\Air\UAV_06\UAV_6_DemineDrone_Bomb_Release_04",
				3.9810717,
				1,
				20
			};
			soundBegin[]=
			{
				"Bomb_Demine_Release_01",
				0.25,
				"Bomb_Demine_Release_02",
				0.25,
				"Bomb_Demine_Release_03",
				0.25,
				"Bomb_Demine_Release_04",
				0.25
			};
		};
	};
};
class CfgSoundSets
{
	class FlareTripMine_Exp_SoundSet
	{
		soundShaders[]=
		{
			"FlareTripMine_Fuse_SoundShader",
			"FlareTripMine_Eject_SoundShader",
			"FlareTripMine_Eject_mechansm_SoundShader"
		};
		volumeFactor=1.6;
		volumeCurve="InverseSquare2Curve";
		spatial=1;
		doppler=0;
		loop=0;
		occlusionFactor=0.60000002;
		obstructionFactor=0.60000002;
		sound3DProcessingType="ExplosionLight3DProcessingType";
		distanceFilter="explosionDistanceFreqAttenuationFilter";
	};
	class FlareTripMine_Tail_SoundSet
	{
		soundShaders[]=
		{
			"FlareTripMine_Eject_TailClose_SoundShader",
			"FlareTripMine_Eject_TailDistant_SoundShader"
		};
		volumeFactor=1;
		volumeCurve="LinearCurve";
		frequencyFactor=1.3;
		spatial=1;
		doppler=0;
		loop=0;
		sound3DProcessingType="WeaponMediumShot3DProcessingType";
		distanceFilter="weaponShotDistanceFreqAttenuationFilter";
		occlusionFactor=0.34999999;
		obstructionFactor=0.34999999;
		frequencyRandomizer=2;
	};
	class UAVLM_Exp_SoundSet
	{
		soundShaders[]=
		{
			"BombsHeavy_closeExp_SoundShader",
			"UAVLM_midExp_SoundShader",
			"BombsHeavy_distExp_SoundShader"
		};
		volumeFactor=1.5;
		volumeCurve="LinearCurve";
		spatial=1;
		doppler=0;
		loop=0;
		sound3DProcessingType="ExplosionHeavy3DProcessingType";
		distanceFilter="explosionDistanceFreqAttenuationFilter";
	};
	class UAVLM_Tail_SoundSet
	{
		soundShaders[]=
		{
			"UAVLM_tailDeep_SoundShader",
			"BombsHeavy_tailForest_SoundShader",
			"BombsHeavy_tailMeadows_SoundShader",
			"BombsHeavy_tailHouses_SoundShader"
		};
		volumeFactor=1;
		volumeCurve="InverseSquare2Curve";
		spatial=1;
		doppler=0;
		loop=0;
		soundShadersLimit=2;
		frequencyRandomizer=0.050000001;
		sound3DProcessingType="ExplosionHeavyTail3DProcessingType";
		distanceFilter="explosionTailDistanceFreqAttenuationFilter";
	};
};
class CfgSoundShaders
{
	class UAVLM_midExp_SoundShader
	{
		samples[]=
		{
			
			{
				"\a3\sounds_f_orange\arsenal\explosives\clusterbomb\cluster_exp_dist_04",
				1
			},
			
			{
				"\a3\sounds_f_orange\arsenal\explosives\clusterbomb\cluster_exp_dist_05",
				1
			},
			
			{
				"\a3\sounds_f_orange\arsenal\explosives\clusterbomb\cluster_exp_dist_07",
				1
			}
		};
		volume=1;
		range=4000;
		rangeCurve[]=
		{
			{0,1},
			{400,1},
			{1000,0.5},
			{4000,0}
		};
	};
	class UAVLM_tailDeep_SoundShader
	{
		samples[]=
		{
			
			{
				"\a3\sounds_f_orange\arsenal\explosives\clusterbomb\cluster_exp_dist_06",
				1
			}
		};
		volume=0.73;
		range=4000;
		rangeCurve[]=
		{
			{0,0},
			{100,0},
			{300,1},
			{4000,1}
		};
	};
	class FlareTripMine_Fuse_SoundShader
	{
		samples[]=
		{
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Fuse_01",
				1
			},
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Fuse_02",
				1
			},
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Fuse_03",
				1
			},
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Fuse_04",
				1
			},
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Fuse_05",
				1
			},
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Fuse_06",
				1
			}
		};
		volume=0.5;
		range=100;
		rangeCurve="closeShotCurve";
	};
	class FlareTripMine_Eject_SoundShader
	{
		samples[]=
		{
			
			{
				"A3\Missions_F_EXP\Data\Sounds\EXP_m04_flare",
				1
			}
		};
		volume=2;
		range=1000;
		rangeCurve="CannonMidShotCurve";
	};
	class FlareTripMine_Eject_mechansm_SoundShader
	{
		samples[]=
		{
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Flag_01",
				1
			},
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Flag_02",
				1
			}
		};
		volume=1;
		range=50;
		rangeCurve="closeShotCurve";
	};
	class FlareTripMine_Eject_TailClose_SoundShader
	{
		samples[]=
		{
			
			{
				"a3\sounds_f_orange\vehicles\air\uav_06\uav_6_deminedrone_dummybomb_report_01",
				1
			},
			
			{
				"a3\sounds_f_orange\vehicles\air\uav_06\uav_6_deminedrone_dummybomb_report_02",
				1
			}
		};
		volume=0.80000007;
		range=1200;
		rangeCurve[]=
		{
			{0,1},
			{300,1},
			{600,0.25},
			{900,0}
		};
	};
	class FlareTripMine_Eject_TailDistant_SoundShader
	{
		samples[]=
		{
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Report_01",
				1
			},
			
			{
				"A3\Sounds_F_Orange\arsenal\explosives\TrainingMine\TrainingMine_Report_02",
				1
			}
		};
		volume=0.5;
		range=1200;
		rangeCurve[]=
		{
			{0,0},
			{500,1},
			{900,0.25},
			{1000,0}
		};
	};
};
class CfgVehicles
{
	class APERSTripMine;
	class FlareTripMine: APERSTripMine
	{
		author="O&T Expansion Eden";
		mapSize=2.0599999;
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\FlareTripMine.jpg";
		_generalMacro="FlareTripMine";
		scope=2;
		ammo="FlareTripMine_Wire_Ammo";
		displayName="$STR_Globe_CfgMagazines_FlareTripMine_Wire_Mag0";
		icon="iconExplosiveAP";
		picture="\A3\Weapons_F\Data\clear_empty.paa";
		model="\A3\Weapons_F\Explosives\Flare_tripwire.p3d";
		descriptionShort="$STR_Globe_CfgMagazines_FlareTripMine_Wire_Mag1";
		class Library
		{
			libTextDesc="$STR_Globe_CfgMagazines_FlareTripMine_Wire_Library0";
		};
	};
};
class UAVLM_Explosion_01
{
	class UAVLM_light
	{
		simulation="light";
		type="UAVLM_light1";
		position[]={0, 1.5, 0};
		intensity=1;
		interval=1;
		lifeTime=0.4;
	};
	class UAVLM_exp
	{
		simulation="particles";
		type="UAVLM_exp1";
		position[]={0,0,0};
		intensity=1;
		interval=1;
		lifeTime=0.2;
	};
};
class UAVLM_Explosion_02
{
	class UAVLM_light
	{
		simulation="light";
		type="UAVLM_light1";
		position[]={0, 0, 0};
		intensity=1;
		interval=1;
		lifeTime=0.4;
	};
	class ClusterSmokeLingering
	{
		simulation="particles";
		type="ClusterSmokeLingering";
		position[]={0,0,0};
		intensity=1;
		interval=1;
		lifeTime=1;
	};
	class Explosion
	{
		simulation="particles";
		type="ExplosionParticles";
		position[]={0,0,0};
		intensity=3;
		interval=1;
		lifeTime=1;
	};
	class Smoke
	{
		simulation="particles";
		type="CloudMedDark";
		position[]={0,0,0};
		intensity=1.5;
		interval=1.2;
		lifeTime=4;
	};
};
class CfgCloudlets
{
	class BombExp1;
	class UAVLM_exp1: BombExp1
	{
		interval=0.01;
		lifeTime=1.2;
		moveVelocity[]={0, 3, 0};
		size[]={4, 7, 10};
		color[]=
		{
			{0.1, 0.1, 0.1, 1},
			{0.15, 0.15, 0.15, 0.7}, 
			{0.2, 0.2, 0.2, 0.3}, 
			{0.3, 0.3, 0.3, 0}
		};
		weight=3;
		rubbing=0.1;
		positionVar[]={3, 2, 3};
		MoveVelocityVar[]={5, 3, 5}; 
	};
};
class CfgLights
{
	class UAVLM_light1
	{
		diffuse[]={1, 0.45, 0.2};
		color[]={1, 0.45, 0.2};
		ambient[]={1, 0.45, 0.2, 0.05};
		brightness=400;
		size=1.5;
		intensity=120000;
		dayLight=1;
		blinking=0;
		useFlare=1;
		flareSize=40;
		flareMaxDistance=1500;
		class Attenuation
		{
			start=5;
			constant=0;
			linear=0;
			quadratic=0.1;
			hardLimitStart=800;
			hardLimitEnd=1600;
		};
		position[]={0, 2.5, 0};
	};
};