class CfgPatches
{
	class A3_Vegetation_F_Vanila_expEden
	{
		author="Trager";
		name="O&T Expansion Eden - Flora";
		url="https://steamcommunity.com/workshop/filedetails/?id=1923321700";
		requiredAddons[]=
		{
			"A3_expEden"
		};
		requiredVersion=0.1;
		units[]=
		{
			"c_Thistle_Thorn_gray",
			"c_Thistle_Thorn_brown",
			"c_Thistle_Small_Yellow",
			"c_Thistle_Small",
			"c_Thistle_Small_GreenYellow",
			"c_Thistle_Medium",
			"c_Thistle_High",
			"c_Thistle_High_Dead",
			"c_GrassCrooked",
			"c_Urchin_black",
			"c_Urchin_black_bunch",
			"c_Urchin_brown",
			"c_Urchin_brown_bunch",
			"c_Urchin_red",
			"c_Urchin_red_bunch",
			"StarFish_01",
			"StarFish_02",
			"c_Spong_tube_green1",
			"c_Spong_tube_green2",
			"c_Spong_tube_green3",
			"c_Spong_tube_green4",
			"c_Spong_tube_yellow1",
			"c_Spong_tube_yellow2",
			"c_Spong_tube_yellow3",
			"c_Spong_tube_yellow4",
			"Seaweed_01",
			"Seaweed_02",
			"SeaDollar_01_red",
			"SeaDollar_01_cyan",
			"SeaDollar_01_pink",
			"SeaDollar_01_purple",
			"SeaDollar_bunch_01",
			"c_Plant_Mullein",
			"c_Plant_Chicory",
			"c_Plant_Dock",
			"c_Plant_Green_Small",
			"c_Plant_GreenBunch",
			"c_GrassLong_DryBunch",
			"c_GrassTall",
			"c_GrassGreen_GroupHard",
			"c_GrassGreen_GroupSoft",
			"c_GrassDesert_GroupHard",
			"c_Grass_Green",
			"c_Grass_TuftDry",
			"c_Grass_Tall_Dead",
			"c_Grass_Dry",
			"c_Grass_Bunch_Small",
			"c_Grass_BrushLow_Sharp",
			"c_Grass_BrushHigh_Dry",
			"c_Grass_BrushHigh_Green",
			"c_Flower_Tansy",
			"c_Coral_SPS_pink_set",
			"c_Coral_SPS_pink_single",
			"c_Crack_Clutter1",
			"c_Crack_Clutter2",
			"c_Crack_Clutter3",
			"c_Crack_Clutter4",
			"c_Flower_BrushMedium_Blue",
			"c_Flower_BrushMedium_White",
			"c_Flower_Cakile",
			"c_Flower_Low_Yellow1",
			"c_Flower_Low_Yellow2",
			"c_Flower_Medium_White1",
			"c_Flower_Medium_White2",
			"c_Coral_plant1",
			"c_Coral_plant2",
			"c_Coral_brain_white",
			"c_Coral_brain_flat1",
			"c_Coral_brain_flat2",
			"c_Coral_brain_flat3",
			"c_Coral_brain_flat4",
			"c_Coral_brain_flat_set1",
			"c_Carduus",
			"t_QuercusIR2s_leaf",
			"t_BroussonetiaP1s_leaf",
			"b_NeriumO2d_leaf",
			"b_NeriumO2s_leaf",
			"b_FicusC1s_leaf",
			"b_Arundo_leaf",
			"t_PopulusN3s_leaf",
			"t_BroussonetiaP1s",
			"t_FicusB1s",
			"t_FicusB2s",
			"t_FraxinusAV2s",
			"t_OleaE1s",
			"t_OleaE2s",
			"t_PhoenixC1s",
			"t_PhoenixC3s",
			"t_PinusP3s",
			"t_PinusS1s",
			"t_PinusS2s_b",
			"t_PinusS2s",
			"t_poplar2f_dead",
			"t_PopulusN3s",
			"t_QuercusIR2s",
			"p_Reeds",
			"b_ArundoD2s",
			"b_ArundoD3s",
			"b_FicusC1s",
			"b_ficusC2d",
			"b_FicusC2s",
			"b_NeriumO2d",
			"b_NeriumO2s",
			"b_NeriumO2s_white",
			"b_Thistle_Thorn_Green"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class Strategic;
	class t_BroussonetiaP1s: Strategic
	{
		author="$STR_A3_Bohemia_Interactive";
		mapSize=0.69999999;
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_BroussonetiaP1s.jpg";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		displayName="$STR_t_BroussonetiaP1s";
		model="\a3\plants_f\tree\t_BroussonetiaP1s_F.p3d";
		_generalMacro="t_BroussonetiaP1s";
		scope=2;
		scopeCurator=2;
		icon="iconObject_1x2";
		editorCategory="EdCat_Vegetation_vanila";
		editorSubcategory="EdSubcat_Tree";
		destrType="DestructTree";
		cost=0;
		affectedByWind=1;
		accuracy=1000;
		armor=1000;
		nameSound="obj_tree";
	};
	class t_BroussonetiaP1s_leaf: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\A3\editorpreviews_f_expEden\data\cfgVehicles\t_BroussonetiaP1s_leaf.jpg";
		_generalMacro="t_BroussonetiaP1s_leaf";
		icon="iconObject_1x4";
		displayName="$STR_Globe_CfgVehicles_t_BroussonetiaP1s_leaf0";
		model="\A3\Plants_F\_Leafs\Leaf_BroussonetiaPapyrifera.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class t_FicusB1s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FicusB1s.jpg";
		_generalMacro="t_FicusB1s";
		icon="iconObject_1x2";
		displayName="$STR_t_FicusB1s";
		model="\a3\plants_f\tree\t_FicusB1s_F.p3d";
	};
	class t_FicusB2s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FicusB2s.jpg";
		_generalMacro="t_FicusB2s";
		icon="iconObject_1x2";
		displayName="$STR_t_FicusB2s";
		model="\a3\plants_f\tree\t_FicusB2s_F.p3d";
	};
	class t_FraxinusAV2s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FraxinusAV2s.jpg";
		_generalMacro="t_FraxinusAV2s";
		icon="iconObject_1x4";
		displayName="$STR_t_FraxinusAV2s";
		model="\a3\plants_f\tree\t_FraxinusAV2s_F.p3d";
	};
	class t_OleaE1s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_OleaE1s.jpg";
		_generalMacro="t_OleaE1s";
		icon="iconObject_1x2";
		displayName="$STR_t_OleaE1s";
		model="\a3\plants_f\tree\t_OleaE1s_F.p3d";
	};
	class t_OleaE2s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_OleaE2s.jpg";
		_generalMacro="t_OleaE2s";
		icon="iconObject_1x2";
		displayName="$STR_t_OleaE2s";
		model="\a3\plants_f\tree\t_OleaE2s_F.p3d";
	};
	class t_OleaE1s_leaf: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_OleaE2s.jpg";
		_generalMacro="t_OleaE1s_leaf";
		icon="iconObject_1x4";
		displayName="$STR_Globe_CfgVehicles_t_OleaE1s_leaf0";
		model="\A3\Plants_F\_Leafs\leaf_OleaEuropaea.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class t_PhoenixC1s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PhoenixC1s.jpg";
		_generalMacro="t_PhoenixC1s";
		icon="iconObject_1x2";
		displayName="$STR_t_PhoenixC1s";
		model="\a3\plants_f\tree\t_PhoenixC1s_F.p3d";
	};
	class t_PhoenixC3s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PhoenixC3s.jpg";
		_generalMacro="t_PhoenixC3s";
		icon="iconObject_1x3";
		displayName="$STR_t_PhoenixC3s";
		model="\a3\plants_f\tree\t_PhoenixC3s_F.p3d";
	};
	class t_PhoenixC1s_leaf: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\A3\editorpreviews_f_expEden\data\cfgVehicles\t_PhoenixC1s_leaf.jpg";
		_generalMacro="t_PhoenixC1s_leaf";
		icon="iconObject_1x4";
		displayName="$STR_Globe_CfgVehicles_t_PhoenixC1s_leaf0";
		model="\A3\Plants_F\_Leafs\leaf_PhoenixCanariensis.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class t_PinusP3s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusP3s.jpg";
		_generalMacro="t_PinusP3s";
		icon="iconObject_1x2";
		displayName="$STR_t_PinusP3s";
		model="\a3\plants_f\tree\t_PinusP3s_F.p3d";
	};
	class t_PinusS1s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusS1s.jpg";
		_generalMacro="t_PinusS1s";
		icon="iconObject_1x2";
		displayName="$STR_t_PinusS1s";
		model="\a3\plants_f\tree\t_PinusS1s_F.p3d";
	};
	class t_PinusS2s_b: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusS2s_b.jpg";
		_generalMacro="t_PinusS2s_b";
		icon="iconObject_1x4";
		displayName="$STR_t_PinusS2s_b";
		model="\a3\plants_f\tree\t_PinusS2s_b_F.p3d";
	};
	class t_PinusS2s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusS2s.jpg";
		_generalMacro="t_PinusS2s";
		icon="iconObject_1x3";
		displayName="$STR_t_PinusS2s";
		model="\a3\plants_f\tree\t_PinusS2s_F.p3d";
	};
	class t_poplar2f_dead: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_poplar2f_dead.jpg";
		_generalMacro="t_poplar2f_dead";
		icon="iconObject_1x2";
		displayName="$STR_t_poplar2f_dead";
		model="\a3\plants_f\tree\t_poplar2f_dead_F.p3d";
	};
	class t_PopulusN3s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PopulusN3s.jpg";
		_generalMacro="t_PopulusN3s";
		icon="iconObject_1x4";
		displayName="$STR_t_PopulusN3s";
		model="\a3\plants_f\tree\t_PopulusN3s_F.p3d";
	};
	class t_PopulusN3s_leaf: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\A3\editorpreviews_f_expEden\data\cfgVehicles\t_PopulusN3s_leaf.jpg";
		_generalMacro="t_PopulusN3s_leaf";
		icon="iconObject_1x4";
		displayName="$STR_Globe_CfgVehicles_t_PopulusN3s_leaf0";
		model="\A3\Plants_F\_Leafs\leaf_PopulusNigra.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class t_QuercusIR2s: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_QuercusIR2s.jpg";
		_generalMacro="t_QuercusIR2s";
		icon="iconObject_1x4";
		displayName="$STR_t_QuercusIR2s";
		model="\a3\plants_f\tree\t_QuercusIR2s_F.p3d";
	};
	class t_QuercusIR2s_leaf: t_BroussonetiaP1s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\A3\editorpreviews_f_expEden\data\cfgVehicles\t_QuercusIR2s_leaf.jpg";
		_generalMacro="t_QuercusIR2s_leaf";
		icon="iconObject_1x4";
		displayName="$STR_Globe_CfgVehicles_t_QuercusIR2s_leaf0";
		model="\A3\Plants_F\_Leafs\leaf_QuercusIlex_Rotundifolia.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class p_Reeds: Strategic
	{
		author="$STR_A3_Bohemia_Interactive";
		mapSize=0.69999999;
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\p_Reeds.jpg";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		displayName="$STR_p_Reeds";
		model="\a3\plants_f\Plant\p_Reeds_F.p3d";
		_generalMacro="p_Reeds";
		scope=2;
		scopeCurator=2;
		icon="iconObject_circle";
		editorCategory="EdCat_Vegetation_vanila";
		editorSubcategory="EdSubcat_Clutter";
		destrType="DestructTent";
		cost=0;
		affectedByWind=1;
		accuracy=1000;
		armor=500;
		nameSound="obj_bush";
	};
	class b_ArundoD2s: Strategic
	{
		author="$STR_A3_Bohemia_Interactive";
		mapSize=0.69999999;
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_ArundoD2s.jpg";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		displayName="$STR_b_ArundoD2s";
		model="\a3\plants_f\Bush\b_ArundoD2s_F.p3d";
		_generalMacro="b_ArundoD2s";
		scope=2;
		scopeCurator=2;
		icon="iconObject_1x1";
		editorCategory="EdCat_Vegetation_vanila";
		editorSubcategory="EdSubcat_Bush";
		destrType="DestructTent";
		cost=0;
		affectedByWind=1;
		accuracy=1000;
		armor=500;
		nameSound="obj_bush";
	};
	class b_ArundoD3s: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_ArundoD3s.jpg";
		_generalMacro="b_ArundoD3s";
		icon="iconObject_3x2";
		displayName="$STR_b_ArundoD3s";
		model="\a3\plants_f\Bush\b_ArundoD3s_F.p3d";
	};
	class b_Arundo_leaf: b_ArundoD2s
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_Arundo_leaf.jpg";
		_generalMacro="b_Arundo_leaf";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_b_Arundo_leaf0";
		model="\A3\Plants_F\_Leafs\Leaf_ArundoDonax.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class b_FicusC1s: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_FicusC1s.jpg";
		_generalMacro="b_FicusC1s";
		icon="iconObject_1x1";
		displayName="$STR_b_FicusC1s";
		model="\a3\plants_f\Bush\b_FicusC1s_F.p3d";
	};
	class b_FicusC1s_leaf: b_ArundoD2s
	{
		scope=1;
		scopeCurator=0;
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_FicusC1s_leaf.jpg";
		_generalMacro="b_FicusC1s_leaf";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_b_FicusC1s_leaf0";
		model="\a3\plants_f\Bush\b_FicusC1s_F.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class b_ficusC2d: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_ficusC2d.jpg";
		_generalMacro="b_ficusC2d";
		icon="iconObject_1x1";
		displayName="$STR_b_ficusC2d";
		model="\a3\plants_f\Bush\b_ficusC2d_F.p3d";
	};
	class b_FicusC2s: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_FicusC2s.jpg";
		_generalMacro="b_FicusC2s";
		icon="iconObject_1x1";
		displayName="$STR_b_FicusC2s";
		model="\a3\plants_f\Bush\b_FicusC2s_F.p3d";
	};
	class b_NeriumO2d: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_NeriumO2d.jpg";
		_generalMacro="b_NeriumO2d";
		icon="iconObject_1x1";
		displayName="$STR_b_NeriumO2d";
		model="\a3\plants_f\Bush\b_NeriumO2d_F.p3d";
	};
	class b_NeriumO2s: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_NeriumO2s.jpg";
		_generalMacro="b_NeriumO2s";
		icon="iconObject_1x1";
		displayName="$STR_b_NeriumO2s";
		model="\a3\plants_f\Bush\b_NeriumO2s_F.p3d";
	};
	class b_NeriumO2s_white: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_NeriumO2s_white.jpg";
		_generalMacro="b_NeriumO2s_white";
		icon="iconObject_1x1";
		displayName="$STR_b_NeriumO2s_white";
		model="\a3\plants_f\Bush\b_NeriumO2s_white_F.p3d";
	};
	class b_NeriumO2s_leaf: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_NeriumO2s_leaf.jpg";
		_generalMacro="b_NeriumO2s_leaf";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_b_NeriumO2s_leaf0";
		model="\A3\Plants_F\_Leafs\leaf_NeriumOleander.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class b_NeriumO2d_leaf: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_NeriumO2d_leaf.jpg";
		_generalMacro="b_NeriumO2d_leaf";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_b_NeriumO2d_leaf0";
		model="\A3\Plants_F\_Leafs\leaf_NeriumOleander_D.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class b_Thistle_Thorn_Green: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_Thistle_Thorn_Green.jpg";
		_generalMacro="b_Thistle_Thorn_Green";
		icon="iconObject_circle";
		displayName="$STR_b_Thistle_Thorn_Green";
		model="\a3\plants_f\Bush\b_Thistle_Thorn_Green.p3d";
	};
	class c_Carduus: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Carduus.jpg";
		_generalMacro="c_Carduus";
		displayName="$STR_b_Thistle_Thorn_Green";
		model="\A3\Plants_F\Clutter\c_Carduus.p3d";
		icon="iconObject_1x4";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Coral_brain: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Carduus.jpg";
		_generalMacro="c_Carduus";
		icon="iconObject_circle";
		displayName="$STR_Globe_CfgVehicles_c_Coral_brain0";
		model="\A3\Plants_F\Clutter\c_Coral_brain.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Coral_brain_flat_set1: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_brain_flat_set1.jpg";
		_generalMacro="c_Coral_brain_flat_set1";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Coral_brain_flat_set10";
		model="\A3\Plants_F\Clutter\c_Coral_brain_flat_set1.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Coral_brain_flat1: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_brain_flat1.jpg";
		_generalMacro="c_Coral_brain_flat1";
		icon="iconObject_1x2";
		displayName="$STR_Globe_CfgVehicles_c_Coral_brain_flat10";
		model="\A3\Plants_F\Clutter\c_Coral_brain_flat1.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Coral_brain_flat2: c_Coral_brain_flat1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_brain_flat2.jpg";
		_generalMacro="c_Coral_brain_flat2";
		displayName="$STR_Globe_CfgVehicles_c_Coral_brain_flat20";
		model="\A3\Plants_F\Clutter\c_Coral_brain_flat2.p3d";
	};
	class c_Coral_brain_flat3: c_Coral_brain_flat1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_brain_flat3.jpg";
		_generalMacro="c_Coral_brain_flat3";
		displayName="$STR_Globe_CfgVehicles_c_Coral_brain_flat30";
		model="\A3\Plants_F\Clutter\c_Coral_brain_flat3.p3d";
	};
	class c_Coral_brain_flat4: c_Coral_brain_flat1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_brain_flat4.jpg";
		_generalMacro="c_Coral_brain_flat4";
		displayName="$STR_Globe_CfgVehicles_c_Coral_brain_flat40";
		model="\A3\Plants_F\Clutter\c_Coral_brain_flat4.p3d";
	};
	class c_Coral_brain_white: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_brain_white.jpg";
		_generalMacro="c_Coral_brain_white";
		icon="iconObject_circle";
		displayName="$STR_Globe_CfgVehicles_c_Coral_brain_white0";
		model="\A3\Plants_F\Clutter\c_Coral_brain_white.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Coral_plant_set1: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_plant_set1.jpg";
		_generalMacro="c_Coral_plant_set1";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Coral_plant_set10";
		model="\A3\Plants_F\Clutter\c_Coral_plant_set1.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Corals_set_t: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Corals_set_t.jpg";
		_generalMacro="c_Corals_set_t";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Corals_set_t0";
		model="\A3\Plants_F\Clutter\c_Corals_set_t.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Coral_plant1: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_plant1.jpg";
		_generalMacro="c_Coral_plant1";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Coral_plant10";
		model="\A3\Plants_F\Clutter\c_Coral_plant1.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Coral_plant2: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_plant2.jpg";
		_generalMacro="c_Coral_plant2";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Coral_plant20";
		model="\A3\Plants_F\Clutter\c_Coral_plant2.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Coral_SPS_pink_set: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_SPS_pink_set.jpg";
		_generalMacro="c_Coral_SPS_pink_set";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Coral_SPS_pink_set0";
		model="\A3\Plants_F\Clutter\c_Coral_SPS_pink_set.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Coral_SPS_pink_single: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Coral_SPS_pink_single.jpg";
		_generalMacro="c_Coral_SPS_pink_single";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Coral_SPS_pink_single0";
		model="\A3\Plants_F\Clutter\c_Coral_SPS_pink_single.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Crack_Clutter1: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Crack_Clutter1.jpg";
		_generalMacro="c_Crack_Clutter1";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Crack_Clutter10";
		model="\A3\Plants_F\Clutter\c_Crack_Clutter1.p3d";
		editorCategory="EdCat_Signs";
		editorSubcategory="EdSubcat_Graffiti";
		vehicleClass="Signs";
	};
	class c_Crack_Clutter2: c_Crack_Clutter1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Crack_Clutter2.jpg";
		_generalMacro="c_Crack_Clutter2";
		icon="iconObject_1x2";
		displayName="$STR_Globe_CfgVehicles_c_Crack_Clutter20";
		model="\A3\Plants_F\Clutter\c_Crack_Clutter2.p3d";
	};
	class c_Crack_Clutter3: c_Crack_Clutter1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Crack_Clutter3.jpg";
		_generalMacro="c_Crack_Clutter3";
		icon="iconObject_1x2";
		displayName="$STR_Globe_CfgVehicles_c_Crack_Clutter30";
		model="\A3\Plants_F\Clutter\c_Crack_Clutter3.p3d";
	};
	class c_Crack_Clutter4: c_Crack_Clutter1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Crack_Clutter4.jpg";
		_generalMacro="c_Crack_Clutter4";
		icon="iconObject_1x2";
		displayName="$STR_Globe_CfgVehicles_c_Crack_Clutter40";
		model="\A3\Plants_F\Clutter\c_Crack_Clutter4.p3d";
	};
	class c_Flower_BrushMedium_Blue: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Flower_BrushMedium_Blue.jpg";
		_generalMacro="c_Flower_BrushMedium_Blue";
		icon="iconObject_circle";
		displayName="$STR_Globe_CfgVehicles_c_Flower_BrushMedium_Blue0";
		model="\A3\Plants_F\Clutter\c_Flower_BrushMedium_Blue.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Flower_BrushMedium_White: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Flower_BrushMedium_White.jpg";
		_generalMacro="c_Flower_BrushMedium_White";
		icon="iconObject_1x2";
		displayName="$STR_Globe_CfgVehicles_c_Flower_BrushMedium_White0";
		model="\A3\Plants_F\Clutter\c_Flower_BrushMedium_White.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Flower_Cakile: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Flower_Cakile.jpg";
		_generalMacro="c_Flower_Cakile";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_c_Flower_Cakile0";
		model="\A3\Plants_F\Clutter\c_Flower_Cakile.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Flower_Low_Yellow1: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Flower_Low_Yellow1.jpg";
		_generalMacro="c_Flower_Low_Yellow1";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Flower_Low_Yellow10";
		model="\A3\Plants_F\Clutter\c_Flower_Low_Yellow1.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Flower_Low_Yellow2: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Flower_Low_Yellow2.jpg";
		_generalMacro="c_Flower_Low_Yellow2";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_c_Flower_Low_Yellow20";
		model="\A3\Plants_F\Clutter\c_Flower_Low_Yellow2.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Flower_Medium_White1: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Flower_Medium_White1.jpg";
		_generalMacro="c_Flower_Medium_White1";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_c_Flower_Medium_White10";
		model="\A3\Plants_F\Clutter\c_Flower_Medium_White1.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Flower_Medium_White2: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Flower_Medium_White2.jpg";
		_generalMacro="c_Flower_Medium_White2";
		icon="iconObject_3x1";
		displayName="$STR_Globe_CfgVehicles_c_Flower_Medium_White20";
		model="\A3\Plants_F\Clutter\c_Flower_Medium_White2.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Flower_Tansy: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Flower_Tansy.jpg";
		_generalMacro="c_Flower_Tansy";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Flower_Tansy0";
		model="\A3\Plants_F\Clutter\c_Flower_Tansy.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Grass_BrushHigh_Green: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Grass_BrushHigh_Green.jpg";
		_generalMacro="c_Grass_BrushHigh_Green";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_c_Grass_BrushHigh_Green0";
		model="\A3\Plants_F\Clutter\c_Grass_BrushHigh_Green.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Grass_BrushHigh_Dry: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Grass_BrushHigh_Dry.jpg";
		_generalMacro="c_Grass_BrushHigh_Dry";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Grass_BrushHigh_Dry0";
		model="\A3\Plants_F\Clutter\c_Grass_BrushHigh_Dry.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Grass_BrushLow_Sharp: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Grass_BrushLow_Sharp.jpg";
		_generalMacro="c_Grass_BrushLow_Sharp";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Grass_BrushLow_Sharp0";
		model="\A3\Plants_F\Clutter\c_Grass_BrushLow_Sharp.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Grass_Bunch_Small: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Grass_Bunch_Small.jpg";
		_generalMacro="c_Grass_Bunch_Small";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Grass_Bunch_Small0";
		model="\A3\Plants_F\Clutter\c_Grass_Bunch_Small.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Grass_Dry: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Grass_Dry.jpg";
		_generalMacro="c_Grass_Dry";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Grass_Dry0";
		model="\A3\Plants_F\Clutter\c_Grass_Dry.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Grass_Tall_Dead: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Grass_Tall_Dead.jpg";
		_generalMacro="c_Grass_Tall_Dead";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Grass_Tall_Dead0";
		model="\A3\Plants_F\Clutter\c_Grass_Tall_Dead.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Grass_TuftDry: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Grass_TuftDry.jpg";
		_generalMacro="c_Grass_TuftDry";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Grass_TuftDry0";
		model="\A3\Plants_F\Clutter\c_Grass_TuftDry.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassDesert_GroupHard: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassDesert_GroupHard.jpg";
		_generalMacro="c_GrassDesert_GroupHard";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_GrassDesert_GroupHard0";
		model="\A3\Plants_F\Clutter\c_GrassDesert_GroupHard.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassGreen_GroupSoft: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassGreen_GroupSoft.jpg";
		_generalMacro="c_GrassGreen_GroupSoft";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_GrassGreen_GroupSoft0";
		model="\A3\Plants_F\Clutter\c_GrassGreen_GroupSoft.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassGreen_GroupHard: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassGreen_GroupHard.jpg";
		_generalMacro="c_GrassGreen_GroupHard";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_GrassGreen_GroupHard0";
		model="\A3\Plants_F\Clutter\c_GrassGreen_GroupHard.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassTall: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassTall.jpg";
		_generalMacro="c_GrassTall";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_c_GrassTall0";
		model="\A3\Plants_F\Clutter\c_GrassTall.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassLong_DryBunch: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassLong_DryBunch.jpg";
		_generalMacro="c_GrassLong_DryBunch";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_GrassLong_DryBunch0";
		model="\A3\Plants_F\Clutter\c_GrassLong_DryBunch.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Plant_Chicory: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Plant_Chicory.jpg";
		_generalMacro="c_Plant_Chicory";
		icon="iconObject_10x1";
		displayName="$STR_Globe_CfgVehicles_c_Plant_Chicory0";
		model="\A3\Plants_F\Clutter\c_Plant_Chicory.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Plant_Dock: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Plant_Dock.jpg";
		_generalMacro="c_Plant_Dock";
		icon="iconObject_4x1";
		displayName="$STR_Globe_CfgVehicles_c_Plant_Dock0";
		model="\A3\Plants_F\Clutter\c_Plant_Dock.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Plant_Green_Small: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Plant_Green_Small.jpg";
		_generalMacro="c_Plant_Green_Small";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Plant_Green_Small0";
		model="\A3\Plants_F\Clutter\c_Plant_Green_Small.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Plant_GreenBunch: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Plant_GreenBunch.jpg";
		_generalMacro="c_Plant_GreenBunch";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Plant_GreenBunch0";
		model="\A3\Plants_F\Clutter\c_Plant_GreenBunch.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Plant_Mullein: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Plant_Mullein.jpg";
		_generalMacro="c_Plant_Mullein";
		icon="iconObject_3x1";
		displayName="$STR_Globe_CfgVehicles_c_Plant_Mullein0";
		model="\A3\Plants_F\Clutter\c_Plant_Mullein.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class SeaDollar_01_red: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\SeaDollar_01_red.jpg";
		_generalMacro="SeaDollar_01_red";
		icon="iconObject_circle";
		displayName="$STR_Globe_CfgVehicles_SeaDollar_01_red0";
		model="\A3\Plants_F\Clutter\c_SeaDollar1.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class SeaDollar_01_cyan: SeaDollar_01_red
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\SeaDollar_01_red.jpg";
		_generalMacro="SeaDollar_01_red";
		displayName="$STR_Globe_CfgVehicles_SeaDollar_01_red0";
		model="\A3\Plants_F\Clutter\c_SeaDollar2.p3d";
	};
	class SeaDollar_01_pink: SeaDollar_01_red
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\SeaDollar_01_pink.jpg";
		_generalMacro="SeaDollar_01_pink";
		displayName="$STR_Globe_CfgVehicles_SeaDollar_01_pink0";
		model="\A3\Plants_F\Clutter\c_SeaDollar3.p3d";
	};
	class SeaDollar_01_purple: SeaDollar_01_red
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\SeaDollar_01_purple.jpg";
		_generalMacro="SeaDollar_01_purple";
		displayName="$STR_Globe_CfgVehicles_SeaDollar_01_purple0";
		model="\A3\Plants_F\Clutter\c_SeaDollar4.p3d";
	};
	class SeaDollar_bunch_01: SeaDollar_01_red
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\SeaDollar_bunch_01.jpg";
		_generalMacro="SeaDollar_bunch_01";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_SeaDollar_bunch_010";
		model="\A3\Plants_F\Clutter\c_SeaDollars_set1.p3d";
	};
	class Seaweed_01: SeaDollar_01_red
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\Seaweed_01.jpg";
		_generalMacro="Seaweed_01";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_Seaweed_010";
		model="\A3\Plants_F\Clutter\c_SeaWeed1.p3d";
	};
	class Seaweed_02: SeaDollar_01_red
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\Seaweed_02.jpg";
		_generalMacro="Seaweed_02";
		icon="iconObject_2x1";
		displayName="$STR_Globe_CfgVehicles_Seaweed_020";
		model="\A3\Plants_F\Clutter\c_SeaWeed2.p3d";
	};
	class c_Spong_tube_green1: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Spong_tube_green1.jpg";
		_generalMacro="c_Spong_tube_green1";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Spong_tube_green10";
		model="\A3\Plants_F\Clutter\c_Spong_tube_green1.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Spong_tube_green2: c_Spong_tube_green1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Spong_tube_green2.jpg";
		_generalMacro="c_Spong_tube_green2";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Spong_tube_green20";
		model="\A3\Plants_F\Clutter\c_Spong_tube_green2.p3d";
	};
	class c_Spong_tube_green3: c_Spong_tube_green1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Spong_tube_green3.jpg";
		_generalMacro="c_Spong_tube_green3";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Spong_tube_green30";
		model="\A3\Plants_F\Clutter\c_Spong_tube_green3.p3d";
	};
	class c_Spong_tube_green4: c_Spong_tube_green1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Spong_tube_green4.jpg";
		_generalMacro="c_Spong_tube_green4";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Spong_tube_green40";
		model="\A3\Plants_F\Clutter\c_Spong_tube_green4.p3d";
	};
	class c_Spong_tube_yellow1: c_Spong_tube_green1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Spong_tube_yellow1.jpg";
		_generalMacro="c_Spong_tube_yellow1";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Spong_tube_yellow10";
		model="\A3\Plants_F\Clutter\c_Spong_tube_yellow1.p3d";
	};
	class c_Spong_tube_yellow2: c_Spong_tube_green1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Spong_tube_yellow2.jpg";
		_generalMacro="c_Spong_tube_yellow2";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Spong_tube_yellow20";
		model="\A3\Plants_F\Clutter\c_Spong_tube_yellow2.p3d";
	};
	class c_Spong_tube_yellow3: c_Spong_tube_green1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Spong_tube_yellow3.jpg";
		_generalMacro="c_Spong_tube_yellow3";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Spong_tube_yellow30";
		model="\A3\Plants_F\Clutter\c_Spong_tube_yellow3.p3d";
	};
	class c_Spong_tube_yellow4: c_Spong_tube_green1
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Spong_tube_yellow4.jpg";
		_generalMacro="c_Spong_tube_yellow4";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Spong_tube_yellow40";
		model="\A3\Plants_F\Clutter\c_Spong_tube_yellow4.p3d";
	};
	class StarFish_01: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\StarFish_01.jpg";
		_generalMacro="StarFish_01";
		icon="iconObject_circle";
		displayName="$STR_Globe_CfgVehicles_StarFish_010";
		model="\A3\Plants_F\Clutter\c_StarFish1.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class StarFish_02: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\StarFish_02.jpg";
		_generalMacro="StarFish_02";
		icon="iconObject_circle";
		displayName="$STR_Globe_CfgVehicles_StarFish_020";
		model="\A3\Plants_F\Clutter\c_StarFish2.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Urchin_black: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Urchin_black.jpg";
		_generalMacro="c_Urchin_black";
		icon="iconObject_circle";
		displayName="$STR_Globe_CfgVehicles_c_Urchin_black0";
		model="\A3\Plants_F\Clutter\c_Urchin_black.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Urchin_black_bunch: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Urchin_black_bunch.jpg";
		_generalMacro="c_Urchin_black_bunch";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Urchin_black_bunch0";
		model="\A3\Plants_F\Clutter\c_urchin_black_grp.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Urchin_brown: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Urchin_brown.jpg";
		_generalMacro="c_Urchin_brown";
		icon="iconObject_circle";
		displayName="$STR_Globe_CfgVehicles_c_Urchin_brown0";
		model="\A3\Plants_F\Clutter\c_Urchin_brown.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Urchin_brown_bunch: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Urchin_brown_bunch.jpg";
		_generalMacro="c_Urchin_brown_bunch";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Urchin_brown_bunch0";
		model="\A3\Plants_F\Clutter\c_Urchin_brown_grp.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Urchin_red: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Urchin_red.jpg";
		_generalMacro="c_Urchin_red";
		icon="iconObject_circle";
		displayName="$STR_Globe_CfgVehicles_c_Urchin_red0";
		model="\A3\Plants_F\Clutter\c_Urchin_red.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Urchin_red_bunch: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Urchin_red_bunch.jpg";
		_generalMacro="c_Urchin_red_bunch";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_Urchin_red_bunch0";
		model="\A3\Plants_F\Clutter\c_urchin_red_grp.p3d";
		editorSubcategory="EdSubcat_Aquatic";
		destrType="DestructNo";
	};
	class c_Thistle_Thorn_gray: b_Thistle_Thorn_Green
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Thistle_Thorn_gray.jpg";
		_generalMacro="c_Thistle_Thorn_gray";
		displayName="$STR_Globe_CfgVehicles_c_Thistle_Thorn_gray0";
		model="\A3\Plants_F\Clutter\c_Thistle_Thorn_Gray.p3d";
	};
	class c_Thistle_Thorn_brown: b_Thistle_Thorn_Green
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Thistle_Thorn_brown.jpg";
		_generalMacro="c_Thistle_Thorn_brown";
		displayName="$STR_Globe_CfgVehicles_c_Thistle_Thorn_brown0";
		model="\A3\Plants_F\Clutter\c_Thistle_Thorn_Brown.p3d";
	};
	class c_Thistle_Small_Yellow: b_Thistle_Thorn_Green
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Thistle_Small_Yellow.jpg";
		_generalMacro="c_Thistle_Small_Yellow";
		displayName="$STR_Globe_CfgVehicles_c_Thistle_Small_Yellow0";
		model="\A3\Plants_F\Clutter\c_Thistle_Small_Yellow.p3d";
		icon="iconObject_1x1";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Thistle_Small: b_Thistle_Thorn_Green
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Thistle_Small.jpg";
		_generalMacro="c_Thistle_Small";
		displayName="$STR_Globe_CfgVehicles_c_Thistle_Small0";
		model="\A3\Plants_F\Clutter\c_Thistle_Small.p3d";
		icon="iconObject_1x1";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Thistle_Small_GreenYellow: b_Thistle_Thorn_Green
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Thistle_Small_GreenYellow.jpg";
		_generalMacro="c_Thistle_Small_GreenYellow";
		displayName="$STR_b_Thistle_Thorn_Green";
		model="\A3\Plants_F\Clutter\c_Thistle_Small_GreenYellow.p3d";
		icon="iconObject_1x2";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Thistle_Medium: b_Thistle_Thorn_Green
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Thistle_Medium.jpg";
		_generalMacro="c_Thistle_Medium";
		displayName="$STR_b_Thistle_Thorn_Green";
		model="\A3\Plants_F\Clutter\c_Thistle_Medium.p3d";
		icon="iconObject_1x4";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Thistle_High: b_Thistle_Thorn_Green
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Thistle_High.jpg";
		_generalMacro="c_Thistle_High";
		displayName="$STR_Globe_CfgVehicles_c_Thistle_High0";
		model="\A3\Plants_F\Clutter\c_Thistle_High.p3d";
	};
	class c_Thistle_High_Dead: b_Thistle_Thorn_Green
	{
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Thistle_High_Dead.jpg";
		_generalMacro="c_Thistle_High_Dead";
		displayName="$STR_Globe_CfgVehicles_c_Thistle_High_Dead0";
		model="\A3\Plants_F\Clutter\c_Thistle_High_Dead.p3d";
	};
	class c_GrassCrooked: b_ArundoD2s
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassCrooked.jpg";
		_generalMacro="c_GrassCrooked";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_GrassCrooked0";
		model="\A3\Plants_F\Clutter\c_GrassCrooked.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
};