class CfgPatches
{
	class A3_Characters_expEden_Loyalists
	{
		addonRootClass="A3_expEden_characters";
		requiredAddons[]=
		{
			"A3_expEden_characters"
		};
		requiredVersion=0.1;
		units[]=
		{
			"B_L_soldier_LAT_F",
			"B_L_soldier_F",
			"B_L_soldier_2_F",
			"B_L_Soldier_3_F",
			"B_L_officer_F",
			"B_L_soldier_M_F",
			"B_L_soldier_M_2_F",
			"B_L_soldier_GL_F",
			"B_L_soldier_AR_2_F",
			"B_L_soldier_AR_F",
			"B_L_soldier_A_2_F",
			"B_L_soldier_A_F"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class B_G_Soldier_F;
	class B_L_Soldier_Base_F: B_G_Soldier_F
	{
		author="O&T Expansion Eden";
		_generalMacro="B_L_Soldier_Base_F";
		scope=1;
		scopeCurator=0;
		editorSubcategory="EdSubcat_Personnel_Loyalists";
		class EventHandlers
		{
			init="if (local (_this # 0)) then {[(_this # 0), false, false] call BIS_fnc_unitHeadgear};";
		};
	};
	class B_L_Soldier_F: B_L_Soldier_Base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_s"
				};
				speechPlural[]=
				{
					"veh_infantry_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_s";
		textPlural="$STR_A3_nameSound_veh_infantry_p";
		nameSound="veh_infantry_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_Soldier_F.jpg";
		_generalMacro="B_L_Soldier_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_CfgVehicles_B_Soldier_F0";
		items[]=
		{
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_HarnessO_brn",
			"H_Cap_tan",
			"G_Bandanna_oli",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessO_brn",
			"H_Cap_tan",
			"G_Bandanna_oli",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		backpack="B_AssaultPack_cbr";
		uniformClass="U_BG_Guerilla3_1";
	};
	class B_L_Soldier_2_F: B_L_Soldier_F
	{
		author="O&T Expansion Eden";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_Soldier_2_F.jpg";
		_generalMacro="B_L_Soldier_2_F";
		linkedItems[]=
		{
			"V_PlateCarrier2_rgr_noflag_F",
			"H_Cap_oli",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier2_rgr_noflag_F",
			"H_Cap_oli",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		backpack="B_AssaultPack_rgr";
		class EventHandlers: EventHandlers
		{
			init="(_this # 0) forceAddUniform 'U_I_C_Soldier_Bandit_3_F'";
		};
	};
	class B_L_Soldier_3_F: B_L_Soldier_F
	{
		author="O&T Expansion Eden";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_Soldier_3_F.jpg";
		_generalMacro="B_L_Soldier_3_F";
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_HeadBandage_bloody_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_HeadBandage_bloody_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_AKS_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKS_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		backpack="";
		uniformClass="U_BG_Guerilla1_1";
	};
	class B_L_soldier_M_F: B_L_Soldier_Base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_sniper_s"
				};
				speechPlural[]=
				{
					"veh_infantry_sniper_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
		nameSound="veh_infantry_sniper_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_soldier_M_F.jpg";
		_generalMacro="B_L_soldier_M_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_M_F0";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		linkedItems[]=
		{
			"V_TacVestIR_blk",
			"H_Shemag_olive",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVestIR_blk",
			"H_Shemag_olive",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"srifle_DMR_06_camo_MRCO_BI_F",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_06_camo_MRCO_BI_F",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		uniformClass="U_BG_Guerilla2_1";
	};
	class B_L_soldier_M_2_F: B_L_soldier_M_F
	{
		author="O&T Expansion Eden";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_soldier_M_2_F.jpg";
		_generalMacro="B_L_soldier_M_2_F";
		linkedItems[]=
		{
			"V_BandollierB_khk",
			"H_Shemag_olive",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_khk",
			"H_Shemag_olive",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"srifle_EBR_MRCO_F",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"srifle_EBR_MRCO_F",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		backpack="B_Carryall_khk";
		class EventHandlers: EventHandlers
		{
			init="(_this # 0) forceAddUniform 'U_I_C_Soldier_Bandit_2_F'";
		};
	};
	class B_L_soldier_GL_F: B_L_Soldier_Base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_s"
				};
				speechPlural[]=
				{
					"veh_infantry_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_s";
		textPlural="$STR_A3_nameSound_veh_infantry_p";
		nameSound="veh_infantry_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_GL_F.jpg";
		_generalMacro="O_A_soldier_GL_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_GL_F0";
		role="Grenadier";
		cost=200000;
		linkedItems[]=
		{
			"V_PlateCarrierIA1_dgtl",
			"H_ShemagOpen_tan",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrierIA1_dgtl",
			"H_ShemagOpen_tan",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_TRG21_GL_MRCO_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_TRG21_GL_MRCO_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"SmokeShellGreen",
			"SmokeShell",
			"MiniGrenade",
			"MiniGrenade",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"SmokeShellGreen",
			"SmokeShell",
			"MiniGrenade",
			"MiniGrenade",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		uniformClass="U_BG_leader";
	};
	class B_L_soldier_AR_F: B_L_Soldier_Base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_MG_s"
				};
				speechPlural[]=
				{
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_soldier_AR_F.jpg";
		_generalMacro="B_L_soldier_AR_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_soldier_AR_F0";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		linkedItems[]=
		{
			"V_PlateCarrierIA1_dgtl",
			"H_Bandanna_khk",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrierIA1_dgtl",
			"H_Bandanna_khk",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"LMG_Mk200_ACO_pointer_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"LMG_Mk200_ACO_pointer_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue"
		};
		backpack="B_AssaultPack_rgr";
		uniformClass="U_BG_Guerilla2_2";
	};
	class B_L_soldier_AR_2_F: B_L_soldier_AR_F
	{
		author="O&T Expansion Eden";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_soldier_AR_2_F.jpg";
		_generalMacro="B_L_soldier_AR_2_F";
		linkedItems[]=
		{
			"V_HarnessO_brn",
			"H_Bandanna_khk",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessO_brn",
			"H_Bandanna_khk",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"LMG_03_Holo_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"LMG_03_Holo_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue"
		};
	};
	class B_L_soldier_LAT_F: B_L_Soldier_Base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_AT_s"
				};
				speechPlural[]=
				{
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_LAT_F.jpg";
		_generalMacro="O_A_soldier_LAT_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_LAT_F0";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		threat[]={0.80000001,0.80000001,0.30000001};
		secondaryAmmoCoef=0.5;
		linkedItems[]=
		{
			"V_PlateCarrierIA2_dgtl",
			"H_MilCap_dgtl",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrierIA2_dgtl",
			"H_MilCap_dgtl",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_AKS_F",
			"launch_RPG32_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKS_F",
			"launch_RPG32_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"RPG32_F",
			"RPG32_F",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"30Rnd_545x39_Mag_F",
			"RPG32_F",
			"RPG32_F",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		backpack="B_Carryall_cbr_LAT_F";
		uniformClass="U_BG_Guerrilla_6_1";
	};
	class B_L_soldier_A_F: B_L_Soldier_Base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_s"
				};
				speechPlural[]=
				{
					"veh_infantry_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_s";
		textPlural="$STR_A3_nameSound_veh_infantry_p";
		nameSound="veh_infantry_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_soldier_A_F.jpg";
		_generalMacro="B_L_soldier_A_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_A_F0";
		items[]=
		{
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Watchcap_cbr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Watchcap_cbr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_MX_SW_Black_BI_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_SW_Black_BI_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_65x39_caseless_black_mag",
			"MiniGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"100Rnd_65x39_caseless_black_mag",
			"MiniGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		backpack="B_AssaultPack_Ammo_rgr";
		uniformClass="U_BG_Guerilla2_1";
	};
	class B_L_soldier_A_2_F: B_L_soldier_A_F
	{
		author="O&T Expansion Eden";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_soldier_A_2_F.jpg";
		_generalMacro="B_L_soldier_A_2_F";
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_EarProtectors_black_F",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_EarProtectors_black_F",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AKM_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class B_L_officer_F: B_L_Soldier_Base_F
	{
		author="O&T Expansion Eden";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\B_L_officer_F.jpg";
		_generalMacro="B_L_officer_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_officer_F0";
		icon="iconManOfficer";
		cost=250000;
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Booniehat_khk_hs",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Booniehat_khk_hs",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		weapons[]=
		{
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		class EventHandlers: EventHandlers
		{
			init="(_this # 0) forceAddUniform 'U_C_Mechanic_01_F'";
		};
	};
};
