class CfgPatches
{
	class A3_Vegetation_F_Enoch_expEden
	{
		author="Trager";
		name="O&T Expansion Eden - Enoch Flora";
		url="https://steamcommunity.com/workshop/filedetails/?id=1923321700";
		requiredAddons[]=
		{
			"A3_expEden"
		};
		requiredVersion=0.1;
		units[]=
		{
			"c_BranchesBig_pine_01",
			"c_BranchesBig_pine_02",
			"c_BranchesBig_pine_03",
			"c_Pines_leaf",
			"c_beech_big",
			"c_beech_mid",
			"c_beech_small",
			"c_branches_deciduous",
			"c_branches_picea",
			"c_branchesBig_picea",
			"c_Cones",
			"c_fern",
			"c_fern_amanita_single",
			"c_fern_boletus_group",
			"c_fernTall",
			"c_Grass",
			"c_Grass_flower1",
			"c_GrassAnthoxanthum",
			"c_GrassAnthoxanthum_bended",
			"c_GrassDry",
			"c_GrassDryCarduus_f",
			"c_GrassDryHypericum",
			"c_GrassDryPlant1",
			"c_GrassDryTall",
			"c_GrassDryTall2",
			"c_GrassDryTall3",
			"c_GrassLow",
			"c_GrassPlant1",
			"c_GrassPlant2",
			"c_GrassSmall",
			"c_GrassSmallConc",
			"c_GrassTall2",
			"c_GrassTall3",
			"c_GrassTiny",
			"c_GrassTinyConc",
			"c_leaves_dead",
			"c_leaves_dead_half",
			"c_Pines",
			"c_plantsSmall1",
			"c_plantsSmall2",
			"c_stubble",
			"c_Vaccinium",
			"c_weat",
			"c_weatTall",
			"B_Betula_nana",
			"B_Caragana_arborescens",
			"B_Corylus_heterophylla_1",
			"B_Corylus_heterophylla_2",
			"b_FagusSylvatica_1f",
			"B_Phragmites_australis",
			"b_PiceaAbies_1f",
			"b_PiceaAbies_1fb",
			"b_prunusSpinosa_1s",
			"b_prunusSpinosa_2s",
			"b_rosaCanina_1s",
			"b_rosaCanina_2s",
			"b_sambucusNigra_1s",
			"b_sambucusNigra_2s",
			"b_Corn_row_F",
			"D_Betula_pendula_stem",
			"D_Betula_pendula_stump",
			"d_FagusSylvatica_fallen",
			"d_FagusSylvatica_fallenb",
			"d_FagusSylvatica_fallenc",
			"d_FagusSylvatica_stumpb",
			"d_FagusSylvatica_stumpc",
			"D_Picea_stem1",
			"D_Picea_stem2",
			"D_Picea_stump",
			"t_acer2s",
			"T_Betula_pendula_1s",
			"T_Betula_pendula_2f",
			"T_Betula_pendula_2s",
			"T_Betula_pendula_2w",
			"T_Betula_pendula_3f",
			"T_Betula_pendula_3s",
			"t_fagus2f",
			"t_fagus2s",
			"t_FagusSylvatica_1f",
			"t_FagusSylvatica_1fb",
			"t_FagusSylvatica_1fc",
			"t_FagusSylvatica_1fd",
			"t_FagusSylvatica_1fe",
			"t_FagusSylvatica_1s",
			"t_FagusSylvatica_2d",
			"t_FagusSylvatica_2f",
			"t_FagusSylvatica_2fb",
			"t_FagusSylvatica_2fc",
			"t_FagusSylvatica_2s",
			"t_FagusSylvatica_2sb",
			"t_FagusSylvatica_3d",
			"t_FagusSylvatica_3f",
			"t_FagusSylvatica_3fb",
			"t_FagusSylvatica_3s",
			"t_juglansRegia_2s",
			"t_juglansRegia_3s",
			"t_malusDomestica_2s",
			"t_malusDomestica_3s",
			"t_PiceaAbies_1f",
			"t_PiceaAbies_1s",
			"t_PiceaAbies_1sb",
			"t_piceaabies_2d",
			"t_PiceaAbies_2f",
			"t_PiceaAbies_2fb",
			"t_PiceaAbies_2s",
			"t_PiceaAbies_2sb",
			"t_piceaabies_3d",
			"t_PiceaAbies_3f",
			"t_PiceaAbies_3s",
			"t_PiceaAbiesNativitatis_2s",
			"t_PinusSylvestris_1f",
			"t_PinusSylvestris_1s",
			"t_PinusSylvestris_2f",
			"t_PinusSylvestris_2fb",
			"t_PinusSylvestris_2s",
			"t_PinusSylvestris_2sb",
			"t_PinusSylvestris_3d",
			"t_PinusSylvestris_3f",
			"t_PinusSylvestris_3fb",
			"t_PinusSylvestris_3fc",
			"t_PinusSylvestris_3s",
			"t_PopulusN3s_F",
			"t_pyrusCommunis_2s",
			"t_pyrusCommunis_3s",
			"t_salix2s",
			"t_sorbus2s",
			"t_stub_picea"
		};
		weapons[]={};
	};
};
class CfgEditorCategories
{
	class EdCat_Vegetation_Enoch
	{
		displayName="$STR_A3_C_CfgEditorCategories_EdCat_Vegetation_Enoch0";
	};
};
class CfgEditorSubcategories
{
	class EdSubcat_Clutter
	{
		displayName="$STR_A3_C_CfgEditorSubcategories_EdSubcat_Clutter0";
	};
	class EdSubcat_Tree
	{
		displayName="$STR_A3_C_CfgEditorSubcategories_EdSubcat_Tree0";
	};
	class EdSubcat_Bush
	{
		displayName="$STR_A3_CfgEditorSubCategories_EdSubcat_Bushes0";
	};
	class EdSubcat_Crop
	{
		displayName="$STR_expEden_EdSubcat_Crop0";
	};
};
class CfgVehicles
{
	class Strategic;
	class ThingX;
	class A3_vegetation_f_enoch_expEden: Strategic
	{
		author="$STR_A3_Bohemia_Interactive";
		mapSize=0.69999999;
		_generalMacro="a3_expEden";
		scope=0;
		scopeCurator=0;
		icon="iconObject_circle";
		editorCategory="EdCat_Vegetation_Enoch";
		editorSubcategory="EdSubcat_Clutter";
		destrType="DestructTree";
		cost=0;
		DLC="Enoch";
		affectedByWind=1;
		accuracy=1000;
		armor=1000;
		class EventHandlers
		{
		};
	};
	class c_beech_big: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_beech_big.jpg";
		_generalMacro="c_beech_big";
		displayName="$STR_c_beech_big";
		model="\a3\vegetation_f_enoch\clutter\c_beech_big.p3d";
		editorSubcategory="EdSubcat_Clutter";
		icon="iconObject_circle";
	};
	class c_beech_mid: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_beech_mid.jpg";
		_generalMacro="c_beech_mid";
		displayName="$STR_c_beech_mid";
		model="\a3\vegetation_f_enoch\clutter\c_beech_mid.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_beech_small: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_beech_small.jpg";
		_generalMacro="c_beech_small";
		displayName="$STR_c_beech_small";
		model="\a3\vegetation_f_enoch\clutter\c_beech_small.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_branches_deciduous: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_branches_deciduous.jpg";
		_generalMacro="c_branches_deciduous";
		displayName="$STR_c_branches_deciduous";
		model="\a3\vegetation_f_enoch\clutter\c_branches_deciduous.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_branches_picea: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_branches_picea.jpg";
		_generalMacro="c_branches_picea";
		displayName="$STR_c_branches_picea";
		model="\a3\vegetation_f_enoch\clutter\c_branches_picea.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_branchesBig_picea: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_branchesBig_picea.jpg";
		_generalMacro="c_branchesBig_picea";
		displayName="$STR_c_branchesBig_picea";
		model="\a3\vegetation_f_enoch\clutter\c_branchesBig_picea.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Cones: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Cones.jpg";
		_generalMacro="c_Cones";
		displayName="$STR_c_Cones";
		model="\a3\vegetation_f_enoch\clutter\c_Cones.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_fern: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_fern.jpg";
		_generalMacro="c_fern";
		displayName="$STR_c_fern";
		model="\a3\vegetation_f_enoch\clutter\c_fern.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_fern_amanita_single: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_fern_amanita_single.jpg";
		_generalMacro="c_fern_amanita_single";
		displayName="$STR_c_fern_amanita_single";
		model="\a3\vegetation_f_enoch\clutter\c_fern_amanita_single.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_fern_boletus_group: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_fern_boletus_group.jpg";
		_generalMacro="c_fern_boletus_group";
		displayName="$STR_c_fern_boletus_group";
		model="\a3\vegetation_f_enoch\clutter\c_fern_boletus_group.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_fernTall: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_fernTall.jpg";
		_generalMacro="c_fernTall";
		displayName="$STR_c_fernTall";
		model="\a3\vegetation_f_enoch\clutter\c_fernTall.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Grass: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Grass.jpg";
		_generalMacro="c_Grass";
		displayName="$STR_ATOC_grass";
		model="\a3\vegetation_f_enoch\clutter\c_Grass.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Grass_flower1: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Grass_flower1.jpg";
		_generalMacro="c_Grass_flower1";
		displayName="$STR_c_Grass_flower1";
		model="\a3\vegetation_f_enoch\clutter\c_Grass_flower1.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassAnthoxanthum: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassAnthoxanthum.jpg";
		_generalMacro="c_GrassAnthoxanthum";
		displayName="$STR_c_GrassAnthoxanthum";
		model="\a3\vegetation_f_enoch\clutter\c_GrassAnthoxanthum.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassAnthoxanthum_bended: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassAnthoxanthum_bended.jpg";
		_generalMacro="c_GrassAnthoxanthum_bended";
		displayName="$STR_c_GrassAnthoxanthum_bended";
		model="\a3\vegetation_f_enoch\clutter\c_GrassAnthoxanthum_bended.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassDry: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassDry.jpg";
		_generalMacro="c_GrassDry";
		displayName="$STR_c_GrassDry";
		model="\a3\vegetation_f_enoch\clutter\c_GrassDry.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassDryCarduus_f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructNo";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassDryCarduus_f.jpg";
		_generalMacro="c_GrassDryCarduus_f";
		displayName="$STR_c_GrassDryCarduus_f";
		model="\a3\vegetation_f_enoch\clutter\c_GrassDryCarduus_f.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassDryHypericum: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassDryHypericum.jpg";
		_generalMacro="c_GrassDryHypericum";
		displayName="$STR_c_GrassDryHypericum";
		model="\a3\vegetation_f_enoch\clutter\c_GrassDryHypericum.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassDryPlant1: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassDryPlant1.jpg";
		_generalMacro="c_GrassDryPlant1";
		displayName="$STR_c_GrassDryPlant1";
		model="\a3\vegetation_f_enoch\clutter\c_GrassDryPlant1.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassDryTall: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassDryTall.jpg";
		_generalMacro="c_GrassDryTall";
		displayName="$STR_c_GrassDryTall";
		model="\a3\vegetation_f_enoch\clutter\c_GrassDryTall.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassDryTall2: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassDryTall2.jpg";
		_generalMacro="c_GrassDryTall2";
		displayName="$STR_c_GrassDryTall2";
		model="\a3\vegetation_f_enoch\clutter\c_GrassDryTall2.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassDryTall3: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassDryTall3.jpg";
		_generalMacro="c_GrassDryTall3";
		displayName="$STR_c_GrassDryTall3";
		model="\a3\vegetation_f_enoch\clutter\c_GrassDryTall3.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassLow: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassLow.jpg";
		_generalMacro="c_GrassLow";
		displayName="$STR_c_GrassLow";
		model="\a3\vegetation_f_enoch\clutter\c_GrassLow.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassPlant1: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassPlant1.jpg";
		_generalMacro="c_GrassPlant1";
		displayName="$STR_c_GrassPlant1";
		model="\a3\vegetation_f_enoch\clutter\c_GrassPlant1.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassPlant2: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassPlant2.jpg";
		_generalMacro="c_GrassPlant2";
		displayName="$STR_c_GrassPlant2";
		model="\a3\vegetation_f_enoch\clutter\c_GrassPlant2.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassSmall: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassSmall.jpg";
		_generalMacro="c_GrassSmall";
		displayName="$STR_c_GrassSmall";
		model="\a3\vegetation_f_enoch\clutter\c_GrassSmall.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassSmallConc: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassSmallConc.jpg";
		_generalMacro="c_GrassSmallConc";
		displayName="$STR_c_GrassSmallConc";
		model="\a3\vegetation_f_enoch\clutter\c_GrassSmallConc.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassTall2: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassTall2.jpg";
		_generalMacro="c_GrassTall2";
		displayName="$STR_c_GrassTall2";
		model="\a3\vegetation_f_enoch\clutter\c_GrassTall2.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassTall3: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassTall3.jpg";
		_generalMacro="c_GrassTall3";
		displayName="$STR_c_GrassTall3";
		model="\a3\vegetation_f_enoch\clutter\c_GrassTall3.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassTiny: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassTiny.jpg";
		_generalMacro="c_GrassTiny";
		displayName="$STR_c_GrassTiny";
		model="\a3\vegetation_f_enoch\clutter\c_GrassTiny.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_GrassTinyConc: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_GrassTinyConc.jpg";
		_generalMacro="c_GrassTinyConc";
		displayName="$STR_c_GrassTinyConc";
		model="\a3\vegetation_f_enoch\clutter\c_GrassTinyConc.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_leaves_dead: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_leaves_dead.jpg";
		_generalMacro="c_leaves_dead";
		displayName="$STR_c_leaves_dead";
		model="\a3\vegetation_f_enoch\clutter\c_leaves_dead.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_leaves_dead_half: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_leaves_dead_half.jpg";
		_generalMacro="c_leaves_dead_half";
		displayName="$STR_c_leaves_dead_half";
		model="\a3\vegetation_f_enoch\clutter\c_leaves_dead_half.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Pines: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Pines.jpg";
		_generalMacro="c_Pines";
		displayName="$STR_c_Pines";
		model="\a3\vegetation_f_enoch\clutter\c_Pines.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Pines_leaf: c_Pines
	{
		destrType="DestructNo";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Pines_leaf.jpg";
		_generalMacro="c_Pines_leaf";
		displayName="$STR_Globe_CfgVehicles_c_Pines_leaf0";
		model="\A3\Plants_F\_Leafs\leaf_Pines.p3d";
	};
	class c_BranchesBig_pine_01: c_Pines
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\A3\editorpreviews_f_expEden\data\cfgVehicles\c_BranchesBig_pine_01.jpg";
		_generalMacro="c_BranchesBig_pine_01";
		icon="iconObject_1x1";
		displayName="$STR_Globe_CfgVehicles_c_BranchesBig_pine_010";
		model="\A3\Plants_F\Clutter\c_bigFallenBranches_pine.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_BranchesBig_pine_02: c_Pines
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\A3\editorpreviews_f_expEden\data\cfgVehicles\c_BranchesBig_pine_02.jpg";
		_generalMacro="c_BranchesBig_pine_02";
		icon="iconObject_1x2";
		displayName="$STR_Globe_CfgVehicles_c_BranchesBig_pine_020";
		model="\A3\Plants_F\Clutter\c_bigFallenBranches_pine02.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_BranchesBig_pine_03: c_Pines
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\A3\editorpreviews_f_expEden\data\cfgVehicles\c_BranchesBig_pine_03.jpg";
		_generalMacro="c_BranchesBig_pine_03";
		icon="iconObject_1x2";
		displayName="$STR_Globe_CfgVehicles_c_BranchesBig_pine_030";
		model="\A3\Plants_F\Clutter\c_bigFallenBranches_pine03.p3d";
		destrType="DestructNo";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_plantsSmall1: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_plantsSmall1.jpg";
		_generalMacro="c_plantsSmall1";
		displayName="$STR_c_plantsSmall1";
		model="\a3\vegetation_f_enoch\clutter\c_plantsSmall1.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_plantsSmall2: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_plantsSmall2.jpg";
		_generalMacro="c_plantsSmall2";
		displayName="$STR_c_plantsSmall2";
		model="\a3\vegetation_f_enoch\clutter\c_plantsSmall2.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_stubble: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_stubble.jpg";
		_generalMacro="c_stubble";
		displayName="$STR_c_stubble";
		model="\a3\vegetation_f_enoch\clutter\c_stubble.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_Vaccinium: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_Vaccinium.jpg";
		_generalMacro="c_Vaccinium";
		displayName="$STR_c_Vaccinium";
		model="\a3\vegetation_f_enoch\clutter\c_Vaccinium.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_weat: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_weat.jpg";
		_generalMacro="c_weat";
		displayName="$STR_c_weat";
		model="\a3\vegetation_f_enoch\clutter\c_weat.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class c_weatTall: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\c_weatTall.jpg";
		_generalMacro="c_weatTall";
		displayName="$STR_c_weatTall";
		model="\a3\vegetation_f_enoch\clutter\c_weatTall.p3d";
		editorSubcategory="EdSubcat_Clutter";
	};
	class B_Betula_nana: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\B_Betula_nana.jpg";
		_generalMacro="B_Betula_nana";
		displayName="$STR_B_Betula_nana";
		model="\a3\vegetation_f_enoch\Bush\B_Betula_nana.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class B_Caragana_arborescens: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\B_Caragana_arborescens.jpg";
		_generalMacro="B_Caragana_arborescens";
		displayName="$STR_B_Caragana_arborescens";
		model="\a3\vegetation_f_enoch\Bush\B_Caragana_arborescens.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class B_Corylus_heterophylla_1: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\B_Corylus_heterophylla_1.jpg";
		_generalMacro="B_Corylus_heterophylla_1";
		displayName="$STR_B_Corylus_heterophylla_1";
		model="\a3\vegetation_f_enoch\Bush\B_Corylus_heterophylla_1.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class B_Corylus_heterophylla_2: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\B_Corylus_heterophylla_2.jpg";
		_generalMacro="B_Corylus_heterophylla_2";
		displayName="$STR_B_Corylus_heterophylla_2";
		model="\a3\vegetation_f_enoch\Bush\B_Corylus_heterophylla_2.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_FagusSylvatica_1f: A3_vegetation_f_enoch_expEden
	{
		icon="iconObject_1x3";
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_FagusSylvatica_1f.jpg";
		_generalMacro="b_FagusSylvatica_1f";
		displayName="$STR_b_FagusSylvatica_1f";
		model="\a3\vegetation_f_enoch\Bush\b_FagusSylvatica_1f.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class B_Phragmites_australis: A3_vegetation_f_enoch_expEden
	{
		icon="iconObject_1x1";
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\B_Phragmites_australis.jpg";
		_generalMacro="B_Phragmites_australis";
		displayName="$STR_B_Phragmites_australis";
		model="\a3\vegetation_f_enoch\Bush\B_Phragmites_australis.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_PiceaAbies_1f: A3_vegetation_f_enoch_expEden
	{
		icon="iconObject_1x3";
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_PiceaAbies_1f.jpg";
		_generalMacro="b_PiceaAbies_1f";
		displayName="$STR_b_PiceaAbies_1f";
		model="\a3\vegetation_f_enoch\Bush\b_PiceaAbies_1f.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_PiceaAbies_1fb: A3_vegetation_f_enoch_expEden
	{
		icon="iconObject_1x3";
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_PiceaAbies_1fb.jpg";
		_generalMacro="b_PiceaAbies_1fb";
		displayName="$STR_b_PiceaAbies_1fb";
		model="\a3\vegetation_f_enoch\Bush\b_PiceaAbies_1fb.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_prunusSpinosa_1s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_prunusSpinosa_1s.jpg";
		_generalMacro="b_prunusSpinosa_1s";
		displayName="$STR_b_prunusSpinosa_1s";
		model="\a3\vegetation_f_enoch\Bush\b_prunusSpinosa_1s.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_prunusSpinosa_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_prunusSpinosa_2s.jpg";
		_generalMacro="b_prunusSpinosa_2s";
		displayName="$STR_b_prunusSpinosa_2s";
		model="\a3\vegetation_f_enoch\Bush\b_prunusSpinosa_2s.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_rosaCanina_1s: A3_vegetation_f_enoch_expEden
	{
		icon="iconObject_1x2";
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_rosaCanina_1s.jpg";
		_generalMacro="b_rosaCanina_1s";
		displayName="$STR_b_rosaCanina_1s";
		model="\a3\vegetation_f_enoch\Bush\b_rosaCanina_1s.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_rosaCanina_2s: A3_vegetation_f_enoch_expEden
	{
		icon="iconObject_1x3";
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_rosaCanina_2s.jpg";
		_generalMacro="b_rosaCanina_2s";
		displayName="$STR_b_rosaCanina_2s";
		model="\a3\vegetation_f_enoch\Bush\b_rosaCanina_2s.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_sambucusNigra_1s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		destrType="DestructTent";
		armor=500;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_sambucusNigra_1s.jpg";
		_generalMacro="b_sambucusNigra_1s";
		displayName="$STR_b_sambucusNigra_1s";
		model="\a3\vegetation_f_enoch\Bush\b_sambucusNigra_1s.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_sambucusNigra_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_sambucusNigra_2s.jpg";
		_generalMacro="b_sambucusNigra_2s";
		displayName="$STR_b_sambucusNigra_2s";
		model="\a3\vegetation_f_enoch\Bush\b_sambucusNigra_2s.p3d";
		editorSubcategory="EdSubcat_Bush";
		nameSound="obj_bush";
	};
	class b_Corn_row_F: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\b_Corn_row_F.jpg";
		_generalMacro="b_Corn_row_F";
		displayName="$STR_b_Corn_row_F";
		model="\a3\vegetation_f_enoch\Crop\b_Corn_row_F.p3d";
		editorSubcategory="EdSubcat_Crop";
	};
	class D_Betula_pendula_stem: ThingX
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=1;
			animate[]={};
			hide[]={};
			verticalOffset=1.247;
			verticalOffsetWorld=0;
			init="''";
		};
		placement="horizontal";
		destrType="DestructNo";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\D_Betula_pendula_stem.jpg";
		_generalMacro="D_Betula_pendula_stem";
		displayName="$STR_D_Betula_pendula_stem";
		model="\a3\vegetation_f_enoch\Tree\D_Betula_pendula_stem.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		mapSize=0.69999999;
		icon="iconObject_10x1";
		editorCategory="EdCat_Vegetation_Enoch";
		cost=0;
		DLC="Enoch";
		affectedByWind=1;
		accuracy=1000;
		armor=10000;
	};
	class D_Betula_pendula_stump: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\D_Betula_pendula_stump.jpg";
		_generalMacro="D_Betula_pendula_stump";
		displayName="$STR_D_Betula_pendula_stump";
		model="\a3\vegetation_f_enoch\Tree\D_Betula_pendula_stump.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class d_FagusSylvatica_fallen: D_Betula_pendula_stem
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=1;
			animate[]={};
			hide[]={};
			verticalOffset=1.247;
			verticalOffsetWorld=0;
			init="''";
		};
		placement="horizontal";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\d_FagusSylvatica_fallen.jpg";
		_generalMacro="d_FagusSylvatica_fallen";
		displayName="$STR_d_FagusSylvatica_fallen";
		model="\a3\vegetation_f_enoch\Tree\d_FagusSylvatica_fallen.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_10x1";
	};
	class d_FagusSylvatica_fallenb: D_Betula_pendula_stem
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=1;
			animate[]={};
			hide[]={};
			verticalOffset=1.247;
			verticalOffsetWorld=0;
			init="''";
		};
		placement="horizontal";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\d_FagusSylvatica_fallenb.jpg";
		_generalMacro="d_FagusSylvatica_fallenb";
		displayName="$STR_d_FagusSylvatica_fallenb";
		model="\a3\vegetation_f_enoch\Tree\d_FagusSylvatica_fallenb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_10x1";
	};
	class d_FagusSylvatica_fallenc: D_Betula_pendula_stem
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=1;
			animate[]={};
			hide[]={};
			verticalOffset=4.2470002;
			verticalOffsetWorld=0;
			init="''";
		};
		placement="horizontal";
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\d_FagusSylvatica_fallenc.jpg";
		_generalMacro="d_FagusSylvatica_fallenc";
		displayName="$STR_d_FagusSylvatica_fallenc";
		model="\a3\vegetation_f_enoch\Tree\d_FagusSylvatica_fallenc.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_10x1";
	};
	class d_FagusSylvatica_stumpb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\d_FagusSylvatica_stumpb.jpg";
		_generalMacro="d_FagusSylvatica_stumpb";
		displayName="$STR_d_FagusSylvatica_stumpb";
		model="\a3\vegetation_f_enoch\Tree\d_FagusSylvatica_stumpb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class d_FagusSylvatica_stumpc: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\d_FagusSylvatica_stumpc.jpg";
		_generalMacro="d_FagusSylvatica_stumpc";
		displayName="$STR_d_FagusSylvatica_stumpc";
		model="\a3\vegetation_f_enoch\Tree\d_FagusSylvatica_stumpc.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class D_Picea_stem1: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\D_Picea_stem1.jpg";
		_generalMacro="D_Picea_stem1";
		displayName="$STR_D_Picea_stem1";
		model="\a3\vegetation_f_enoch\Tree\D_Picea_stem1.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class D_Picea_stem2: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\D_Picea_stem2.jpg";
		_generalMacro="D_Picea_stem2";
		displayName="$STR_D_Picea_stem2";
		model="\a3\vegetation_f_enoch\Tree\D_Picea_stem2.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class D_Picea_stump: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\D_Picea_stump.jpg";
		_generalMacro="D_Picea_stump";
		displayName="$STR_D_Picea_stump";
		model="\a3\vegetation_f_enoch\Tree\D_Picea_stump.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_acer2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_acer2s.jpg";
		_generalMacro="t_acer2s";
		displayName="$STR_t_acer2s";
		model="\a3\vegetation_f_enoch\Tree\t_acer2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class T_Betula_pendula_1s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\T_Betula_pendula_1s.jpg";
		_generalMacro="T_Betula_pendula_1s";
		displayName="$STR_T_Betula_pendula_1s";
		model="\a3\vegetation_f_enoch\Tree\T_Betula_pendula_1s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_1x2";
	};
	class T_Betula_pendula_2f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\T_Betula_pendula_2f.jpg";
		_generalMacro="T_Betula_pendula_2f";
		displayName="$STR_T_Betula_pendula_2f";
		model="\a3\vegetation_f_enoch\Tree\T_Betula_pendula_2f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_1x4";
	};
	class T_Betula_pendula_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\T_Betula_pendula_2s.jpg";
		_generalMacro="T_Betula_pendula_2s";
		displayName="$STR_T_Betula_pendula_2s";
		model="\a3\vegetation_f_enoch\Tree\T_Betula_pendula_2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_1x3";
	};
	class T_Betula_pendula_2w: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\T_Betula_pendula_2w.jpg";
		_generalMacro="T_Betula_pendula_2w";
		displayName="$STR_T_Betula_pendula_2w";
		model="\a3\vegetation_f_enoch\Tree\T_Betula_pendula_2w.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_1x2";
	};
	class T_Betula_pendula_3f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\T_Betula_pendula_3f.jpg";
		_generalMacro="T_Betula_pendula_3f";
		displayName="$STR_T_Betula_pendula_3f";
		model="\a3\vegetation_f_enoch\Tree\T_Betula_pendula_3f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_1x7";
	};
	class T_Betula_pendula_3s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\T_Betula_pendula_3s.jpg";
		_generalMacro="T_Betula_pendula_3s";
		displayName="$STR_T_Betula_pendula_3s";
		model="\a3\vegetation_f_enoch\Tree\T_Betula_pendula_3s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_1x5";
	};
	class t_fagus2f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_fagus2f.jpg";
		_generalMacro="t_fagus2f";
		displayName="$STR_t_fagus2f";
		model="\a3\vegetation_f_enoch\Tree\t_fagus2f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_fagus2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_fagus2s.jpg";
		_generalMacro="t_fagus2s";
		displayName="$STR_t_fagus2s";
		model="\a3\vegetation_f_enoch\Tree\t_fagus2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_1f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_1f.jpg";
		_generalMacro="t_FagusSylvatica_1f";
		displayName="$STR_t_FagusSylvatica_1f";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_1f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_1fb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_1f.jpg";
		_generalMacro="t_FagusSylvatica_1fb";
		displayName="$STR_t_FagusSylvatica_1fb";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_1fb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_1fc: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_1fc.jpg";
		_generalMacro="t_FagusSylvatica_1fc";
		displayName="$STR_t_FagusSylvatica_1fc";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_1fc.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_1fd: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_1fd.jpg";
		_generalMacro="t_FagusSylvatica_1fd";
		displayName="$STR_t_FagusSylvatica_1fd";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_1fd.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_1fe: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_1fe.jpg";
		_generalMacro="t_FagusSylvatica_1fe";
		displayName="$STR_t_FagusSylvatica_1fe";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_1fe.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_1s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_1s.jpg";
		_generalMacro="t_FagusSylvatica_1s";
		displayName="$STR_t_FagusSylvatica_1s";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_1s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_2d: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_2d.jpg";
		_generalMacro="t_FagusSylvatica_2d";
		displayName="$STR_t_FagusSylvatica_2d";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_2d.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_2f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_2f.jpg";
		_generalMacro="t_FagusSylvatica_2f";
		displayName="$STR_t_FagusSylvatica_2f";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_2f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_2fb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_2fb.jpg";
		_generalMacro="t_FagusSylvatica_2fb";
		displayName="$STR_t_FagusSylvatica_2fb";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_2fb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_2fc: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_2fc.jpg";
		_generalMacro="t_FagusSylvatica_2fc";
		displayName="$STR_t_FagusSylvatica_2fc";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_2fc.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_2s.jpg";
		_generalMacro="t_FagusSylvatica_2s";
		displayName="$STR_t_FagusSylvatica_2s";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_2sb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_2sb.jpg";
		_generalMacro="t_FagusSylvatica_2sb";
		displayName="$STR_t_FagusSylvatica_2sb";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_2sb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_3d: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_3d.jpg";
		_generalMacro="t_FagusSylvatica_3d";
		displayName="$STR_t_FagusSylvatica_3d";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_3d.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_3f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_3f.jpg";
		_generalMacro="t_FagusSylvatica_3f";
		displayName="$STR_t_FagusSylvatica_3f";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_3f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_3fb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_3fb.jpg";
		_generalMacro="t_FagusSylvatica_3fb";
		displayName="$STR_t_FagusSylvatica_3fb";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_3fb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_FagusSylvatica_3s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_FagusSylvatica_3s.jpg";
		_generalMacro="t_FagusSylvatica_3s";
		displayName="$STR_t_FagusSylvatica_3s";
		model="\a3\vegetation_f_enoch\Tree\t_FagusSylvatica_3s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_juglansRegia_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_juglansRegia_2s.jpg";
		_generalMacro="t_juglansRegia_2s";
		displayName="$STR_t_juglansRegia_2s";
		model="\a3\vegetation_f_enoch\Tree\t_juglansRegia_2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_juglansRegia_3s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_juglansRegia_3s.jpg";
		_generalMacro="t_juglansRegia_3s";
		displayName="$STR_t_juglansRegia_3s";
		model="\a3\vegetation_f_enoch\Tree\t_juglansRegia_3s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_malusDomestica_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_malusDomestica_2s.jpg";
		_generalMacro="t_malusDomestica_2s";
		displayName="$STR_t_malusDomestica_2s";
		model="\a3\vegetation_f_enoch\Tree\t_malusDomestica_2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_malusDomestica_3s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_malusDomestica_3s.jpg";
		_generalMacro="t_malusDomestica_3s";
		displayName="$STR_t_malusDomestica_3s";
		model="\a3\vegetation_f_enoch\Tree\t_malusDomestica_3s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbies_1f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbies_1f.jpg";
		_generalMacro="t_PiceaAbies_1f";
		displayName="$STR_t_PiceaAbies_1f";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbies_1f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbies_1s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbies_1s.jpg";
		_generalMacro="t_PiceaAbies_1s";
		displayName="$STR_t_PiceaAbies_1s";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbies_1s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbies_1sb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbies_1sb.jpg";
		_generalMacro="t_PiceaAbies_1sb";
		displayName="$STR_t_PiceaAbies_1sb";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbies_1sb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_piceaabies_2d: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_piceaabies_2d.jpg";
		_generalMacro="t_piceaabies_2d";
		displayName="$STR_t_piceaabies_2d";
		model="\a3\vegetation_f_enoch\Tree\t_piceaabies_2d.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbies_2f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbies_2f.jpg";
		_generalMacro="t_PiceaAbies_2f";
		displayName="$STR_t_PiceaAbies_2f";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbies_2f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbies_2fb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbies_2fb.jpg";
		_generalMacro="t_PiceaAbies_2fb";
		displayName="$STR_t_PiceaAbies_2fb";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbies_2fb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbies_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbies_2s.jpg";
		_generalMacro="t_PiceaAbies_2s";
		displayName="$STR_t_PiceaAbies_2s";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbies_2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbies_2sb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbies_2sb.jpg";
		_generalMacro="t_PiceaAbies_2sb";
		displayName="$STR_t_PiceaAbies_2sb";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbies_2sb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_piceaabies_3d: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_piceaabies_3d.jpg";
		_generalMacro="t_piceaabies_3d";
		displayName="$STR_t_piceaabies_3d";
		model="\a3\vegetation_f_enoch\Tree\t_piceaabies_3d.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbies_3f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbies_3f.jpg";
		_generalMacro="t_PiceaAbies_3f";
		displayName="$STR_t_PiceaAbies_3f";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbies_3f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbies_3s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbies_3s.jpg";
		_generalMacro="t_PiceaAbies_3s";
		displayName="$STR_t_PiceaAbies_3s";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbies_3s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PiceaAbiesNativitatis_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PiceaAbiesNativitatis_2s.jpg";
		_generalMacro="t_PiceaAbiesNativitatis_2s";
		displayName="$STR_t_PiceaAbiesNativitatis_2s";
		model="\a3\vegetation_f_enoch\Tree\t_PiceaAbiesNativitatis_2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_PinusSylvestris_1f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_1f.jpg";
		_generalMacro="t_PinusSylvestris_1f";
		displayName="$STR_t_PinusSylvestris_1f";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_1f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_1x2";
	};
	class t_PinusSylvestris_1s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_1s.jpg";
		_generalMacro="t_PinusSylvestris_1s";
		displayName="$STR_t_PinusSylvestris_1s";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_1s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_1x1";
	};
	class t_PinusSylvestris_2f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_2f.jpg";
		_generalMacro="t_PinusSylvestris_2f";
		displayName="$STR_t_PinusSylvestris_2f";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_2f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_10x1";
	};
	class t_PinusSylvestris_2fb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_2fb.jpg";
		_generalMacro="t_PinusSylvestris_2fb";
		displayName="$STR_t_PinusSylvestris_2fb";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_2fb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_10x1";
	};
	class t_PinusSylvestris_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_2s.jpg";
		_generalMacro="t_PinusSylvestris_2s";
		displayName="$STR_t_PinusSylvestris_2s";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_7x1";
	};
	class t_PinusSylvestris_2sb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_2sb.jpg";
		_generalMacro="t_PinusSylvestris_2sb";
		displayName="$STR_t_PinusSylvestris_2sb";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_2sb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_5x1";
	};
	class t_PinusSylvestris_3d: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_3d.jpg";
		_generalMacro="t_PinusSylvestris_3d";
		displayName="$STR_t_PinusSylvestris_3d";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_3d.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_5x1";
	};
	class t_PinusSylvestris_3f: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_3f.jpg";
		_generalMacro="t_PinusSylvestris_3f";
		displayName="$STR_t_PinusSylvestris_3f";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_3f.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_10x1";
	};
	class t_PinusSylvestris_3fb: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_3fb.jpg";
		_generalMacro="t_PinusSylvestris_3fb";
		displayName="$STR_t_PinusSylvestris_3fb";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_3fb.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_7x1";
	};
	class t_PinusSylvestris_3fc: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_3fc.jpg";
		_generalMacro="t_PinusSylvestris_3fc";
		displayName="$STR_t_PinusSylvestris_3fc";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_3fc.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_7x1";
	};
	class t_PinusSylvestris_3s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PinusSylvestris_3s.jpg";
		_generalMacro="t_PinusSylvestris_3s";
		displayName="$STR_t_PinusSylvestris_3s";
		model="\a3\vegetation_f_enoch\Tree\t_PinusSylvestris_3s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_5x1";
	};
	class t_PopulusN3s_F: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_PopulusN3s_F.jpg";
		_generalMacro="t_PopulusN3s_F";
		displayName="$STR_t_PopulusN3s_F";
		model="\a3\vegetation_f_enoch\Tree\t_PopulusN3s_F.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
		icon="iconObject_1x4";
	};
	class t_pyrusCommunis_2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_pyrusCommunis_2s.jpg";
		_generalMacro="t_pyrusCommunis_2s";
		displayName="$STR_t_pyrusCommunis_2s";
		model="\a3\vegetation_f_enoch\Tree\t_pyrusCommunis_2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_pyrusCommunis_3s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_pyrusCommunis_3s.jpg";
		_generalMacro="t_pyrusCommunis_3s";
		displayName="$STR_t_pyrusCommunis_3s";
		model="\a3\vegetation_f_enoch\Tree\t_pyrusCommunis_3s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_salix2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_salix2s.jpg";
		_generalMacro="t_salix2s";
		displayName="$STR_t_salix2s";
		model="\a3\vegetation_f_enoch\Tree\t_salix2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_sorbus2s: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_sorbus2s.jpg";
		_generalMacro="t_sorbus2s";
		displayName="$STR_t_sorbus2s";
		model="\a3\vegetation_f_enoch\Tree\t_sorbus2s.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
	class t_stub_picea: A3_vegetation_f_enoch_expEden
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.24699999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\a3\editorpreviews_f_expEden\data\cfgVehicles\t_stub_picea.jpg";
		_generalMacro="t_stub_picea";
		displayName="$STR_t_stub_picea";
		model="\a3\vegetation_f_enoch\Tree\t_stub_picea.p3d";
		editorSubcategory="EdSubcat_Tree";
		nameSound="obj_tree";
	};
};
