class CfgPatches
{
	class A3_Characters_expEden_proAAF
	{
		addonRootClass="A3_expEden_characters";
		requiredAddons[]=
		{
			"A3_expEden_characters"
		};
		requiredVersion=0.1;
		units[]=
		{
			"I_P_Soldier_SL_02_F",
			"I_P_Soldier_SL_01_F",
			"I_P_Soldier_02_F",
			"I_P_Soldier_01_F",
			"I_P_medic_02_F",
			"I_P_medic_01_F",
			"I_P_Soldier_AR_01_F",
			"I_P_Soldier_AR_02_F",
			"I_P_Soldier_AR_03_F",
			"I_P_Soldier_M_01_F",
			"I_P_Sniper_F",
			"I_P_officer_F",
			"I_P_Soldier_exp_F"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class I_Soldier_base_F;
	class I_P_Soldier_base_F: I_Soldier_base_F
	{
		author="O&T Expansion Eden";
		_generalMacro="I_P_Soldier_base_F";
		identityTypes[]=
		{
			"LanguageGRE_F",
			"Head_Greek",
			"G_GUERIL_default"
		};
		faceType="Man_A3";
		side=2;
		faction="IND_F";
		genericNames="GreekMen";
		vehicleClass="Men";
		editorSubcategory="EdSubcat_Personnel_AkhanterosRebels";
		portrait="";
		picture="";
		icon="iconMan";
		accuracy=3.9000001;
		camouflage=1.1;
		minFireTime=10;
		model="\A3\characters_F_gamma\Guerrilla\ig_guerrilla1_1.p3d";
		modelSides[]={2,3};
		nakedUniform="U_BasicBody";
		uniformClass="U_IG_Guerilla1_1";
		canCarryBackPack=1;
		scope=1;
		scopeCurator=0;
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"A3\Characters_F\Civil\Data\c_cloth1.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth1_injury.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth1_injury.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth2.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth2_injury.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth2_injury.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth3.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth3_injury.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth3_injury.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth4.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth4_injury.rvmat",
				"A3\Characters_F\Civil\Data\c_cloth4_injury.rvmat",
				"a3\characters_f_epb\blufor\data\clothing1_dirty.rvmat",
				"A3\Characters_F\BLUFOR\Data\clothing1_injury.rvmat",
				"A3\Characters_F\BLUFOR\Data\clothing1_injury.rvmat",
				"A3\characters_f\civil\data\c_poloshirt.rvmat",
				"A3\Characters_F\Civil\Data\c_poloshirt_injury.rvmat",
				"A3\Characters_F\Civil\Data\c_poloshirt_injury.rvmat",
				"A3\characters_f\common\data\coveralls.rvmat",
				"A3\Characters_F\Common\Data\coveralls_injury.rvmat",
				"A3\Characters_F\Common\Data\coveralls_injury.rvmat",
				"A3\Characters_F\Civil\Data\hunter.rvmat",
				"A3\Characters_F\Civil\Data\hunter_injury.rvmat",
				"A3\Characters_F\Civil\Data\hunter_injury.rvmat",
				"a3\characters_f_beta\indep\data\ia_soldier_01_clothing.rvmat",
				"A3\Characters_F_Beta\INDEP\Data\ia_soldier_01_clothing_injury.rvmat",
				"A3\Characters_F_Beta\INDEP\Data\ia_soldier_01_clothing_injury.rvmat",
				"a3\characters_f_gamma\guerrilla\data\ig_guerrilla2_1.rvmat",
				"A3\Characters_F_Gamma\Guerrilla\Data\ig_guerrilla2_1_injury.rvmat",
				"A3\Characters_F_Gamma\Guerrilla\Data\ig_guerrilla2_1_injury.rvmat",
				"a3\characters_f_gamma\guerrilla\data\ig_guerrilla3_1.rvmat",
				"A3\Characters_F\Civil\Data\hunter_injury.rvmat",
				"A3\Characters_F\Civil\Data\hunter_injury.rvmat",
				"a3\characters_f_epb\guerrilla\data\ig_guerrilla4_1.rvmat",
				"A3\Characters_F_EPB\Guerrilla\Data\ig_guerrilla4_1_injury.rvmat",
				"A3\Characters_F_EPB\Guerrilla\Data\ig_guerrilla4_1_injury.rvmat",
				"a3\characters_f_bootcamp\guerrilla\data\ig_guerrilla_6_1.rvmat",
				"A3\Characters_F_Bootcamp\Guerrilla\Data\ig_guerrilla_6_1_injury.rvmat",
				"A3\Characters_F_Bootcamp\Guerrilla\Data\ig_guerrilla_6_1_injury.rvmat",
				"a3\characters_f_beta\indep\data\officer.rvmat",
				"A3\Characters_F_Beta\INDEP\Data\officer_injury.rvmat",
				"A3\Characters_F_Beta\INDEP\Data\officer_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		hiddenSelections[]=
		{
			"Camo",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Gamma\Guerrilla\Data\ig_guerrilla2_1_co.paa"
		};
		class EventHandlers
		{
			init="if (local (_this # 0)) then {(_this # 0) setVariable ['BIS_enableRandomization',false]};";
		};
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"arifle_TRG21_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_TRG21_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Shemag_olive",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Shemag_olive",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class I_P_Soldier_exp_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		_generalMacro="I_P_Soldier_exp_F";
		displayName="$STR_B_Soldier_exp_F0";
		scope=2;
		scopeCurator=2;
		camouflage=1.6;
		backpack="G_Carryall_Exp";
		weapons[]=
		{
			"arifle_Mk20C_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_Mk20C_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"MiniGrenade",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSBoundingMine_Range_Mag",
			"APERSBoundingMine_Range_Mag",
			"SLAMDirectionalMine_Wire_Mag",
			"DemoCharge_Remote_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"MiniGrenade",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSBoundingMine_Range_Mag",
			"APERSBoundingMine_Range_Mag",
			"SLAMDirectionalMine_Wire_Mag",
			"DemoCharge_Remote_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		canDeactivateMines=1;
		detectSkill=38;
		linkedItems[]=
		{
			"V_Chestrig_blk",
			"H_Helmet_Skate",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_blk",
			"H_Helmet_Skate",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		icon="iconManExplosive";
		role="Sapper";
		picture="pictureExplosive";
		model="\A3\characters_F_gamma\Guerrilla\ig_guerrilla2_1.p3d";
		uniformClass="U_IG_Guerilla2_1";
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_Helmet_Skate"
		};
		headgearList[]=
		{
			"G_Balaclava_blk",
			1
		};
	};
	class I_P_officer_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_officer_s"
				};
				speechPlural[]=
				{
					"veh_infantry_officer_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_officer_s";
		textPlural="$STR_A3_nameSound_veh_infantry_officer_p";
		nameSound="veh_infantry_officer_s";
		_generalMacro="I_P_officer_F";
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"A3\Characters_F_Beta\INDEP\Data\officer.rvmat",
				"A3\Characters_F_Beta\INDEP\Data\officer_injury.rvmat",
				"A3\Characters_F_Beta\INDEP\Data\officer_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		cost=250000;
		camouflage=1.6;
		icon="iconManOfficer";
		role="Rifleman";
		displayName="$STR_B_officer_F0";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"arifle_AKM_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"arifle_AKM_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"30Rnd_762x39_Mag_F",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_PASGT_basic_olive_F",
			"G_Balaclava_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_PASGT_basic_olive_F",
			"G_Balaclava_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="U_IG_Guerilla2_3";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\ig_guerrilla2_3_co.paa"
		};
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_PASGT_basic_olive_F"
		};
		headgearList[]=
		{
			"H_PASGT_basic_olive_F",
			1
		};
	};
	class I_P_Sniper_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_sniper_s"
				};
				speechPlural[]=
				{
					"veh_infantry_sniper_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
		nameSound="veh_infantry_sniper_s";
		identityTypes[]=
		{
			"LanguageGRE_F",
			"Head_Greek",
			"G_NATO_sniper"
		};
		primaryAmmoCoef=0.2;
		secondaryAmmoCoef=0.050000001;
		handgunAmmoCoef=0.1;
		threat[]={0.80000001,0.30000001,0.30000001};
		_generalMacro="I_P_Sniper_F";
		displayName="$STR_B_Soldier_M_F0";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"srifle_GM6_MRCO_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_GM6_MRCO_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"5Rnd_127x108_Mag",
			"5Rnd_127x108_Mag",
			"5Rnd_127x108_Mag",
			"5Rnd_127x108_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"5Rnd_127x108_Mag",
			"5Rnd_127x108_Mag",
			"5Rnd_127x108_Mag",
			"5Rnd_127x108_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		cost=250000;
		role="Marksman";
		linkedItems[]=
		{
			"V_BandollierB_khk",
			"H_PASGT_basic_black_F",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_khk",
			"H_PASGT_basic_black_F",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		model="\A3\characters_F_gamma\Guerrilla\ig_guerrilla3_1.p3d";
		uniformClass="U_IG_Guerilla3_1";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Gamma\Guerrilla\Data\ig_guerrilla3_1_co.paa"
		};
		headgearProbability=60;
		allowedHeadgear[]=
		{
			"H_PASGT_basic_black_F"
		};
		headgearList[]=
		{
			"H_PASGT_basic_black_F",
			1
		};
	};
	class I_P_Soldier_M_01_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		_generalMacro="I_P_Soldier_M_01_F";
		displayName="$STR_B_Soldier_M_F0";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"arifle_Mk20_MRCO_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_Mk20_MRCO_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		cost=250000;
		role="Marksman";
		linkedItems[]=
		{
			"V_BandollierB_khk",
			"H_PASGT_basic_olive_F",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_khk",
			"H_PASGT_basic_olive_F",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		model="\A3\characters_F_gamma\Guerrilla\ig_guerrilla3_1.p3d";
		uniformClass="U_IG_Guerilla3_1";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Gamma\Guerrilla\Data\ig_guerrilla3_1_co.paa"
		};
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_PASGT_basic_olive_F"
		};
		headgearList[]=
		{
			"H_PASGT_basic_olive_F",
			1
		};
	};
	class I_P_Soldier_AR_01_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_MG_s"
				};
				speechPlural[]=
				{
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		_generalMacro="I_P_Soldier_AR_01_F";
		displayName="$STR_B_Soldier_AR_F0";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"LMG_Mk200_BI_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"LMG_Mk200_BI_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		cost=220000;
		icon="iconManMG";
		role="MachineGunner";
		linkedItems[]=
		{
			"V_TacVest_camo",
			"H_HelmetIA",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_camo",
			"H_HelmetIA",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		model="\A3\characters_F_gamma\Guerrilla\ig_guerrilla2_1.p3d";
		uniformClass="U_BG_leader";
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_HelmetIA"
		};
		headgearList[]=
		{
			"H_HelmetIA",
			1
		};
	};
	class I_P_Soldier_AR_03_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_MG_s"
				};
				speechPlural[]=
				{
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		_generalMacro="I_P_Soldier_AR_03_F";
		displayName="$STR_B_Soldier_AR_F0";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"LMG_Mk200_BI_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"LMG_Mk200_BI_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		cost=220000;
		icon="iconManMG";
		role="MachineGunner";
		linkedItems[]=
		{
			"V_TacVest_blk",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_blk",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		model="\A3\characters_F_gamma\Guerrilla\ig_guerrilla2_1.p3d";
		uniformClass="U_IG_Guerilla2_1";
	};
	class I_P_Soldier_AR_02_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_MG_s"
				};
				speechPlural[]=
				{
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		_generalMacro="I_P_Soldier_AR_02_F";
		displayName="$STR_B_Soldier_AR_F0";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"arifle_AK12_Holo_pointer_BI_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AK12_Holo_pointer_BI_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"75Rnd_762x39_Mag_F",
			"75Rnd_762x39_Mag_F",
			"75Rnd_762x39_Mag_F",
			"75Rnd_762x39_Mag_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"75Rnd_762x39_Mag_F",
			"75Rnd_762x39_Mag_F",
			"75Rnd_762x39_Mag_F",
			"75Rnd_762x39_Mag_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		cost=220000;
		icon="iconManMG";
		role="MachineGunner";
		linkedItems[]=
		{
			"V_TacVest_blk",
			"H_HelmetIA",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_blk",
			"H_HelmetIA",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		model="\A3\characters_F_gamma\Guerrilla\ig_guerrilla2_1.p3d";
		uniformClass="U_BG_Guerilla1_1";
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_HelmetIA"
		};
		headgearList[]=
		{
			"H_HelmetIA",
			1
		};
	};
	class I_P_medic_01_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_medic_s"
				};
				speechPlural[]=
				{
					"veh_infantry_medic_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_medic_s";
		textPlural="$STR_A3_nameSound_veh_infantry_medic_p";
		nameSound="veh_infantry_medic_s";
		_generalMacro="I_P_medic_01_F";
		displayName="$STR_B_medic_F0";
		scope=2;
		scopeCurator=2;
		backpack="G_FieldPack_Medic";
		weapons[]=
		{
			"arifle_Mk20_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_Mk20_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnmagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_TacVest_blk",
			"H_HelmetIA",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_blk",
			"H_HelmetIA",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		attendant=1;
		icon="iconManMedic";
		role="CombatLifeSaver";
		picture="pictureHeal";
		model="\A3\characters_F_gamma\Guerrilla\ig_guerrilla2_1.p3d";
		uniformClass="U_C_Poor_1";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\ig_guerrilla2_3_co.paa"
		};
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_HelmetIA"
		};
		headgearList[]=
		{
			"H_HelmetIA",
			1
		};
	};
	class I_P_medic_02_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_medic_s"
				};
				speechPlural[]=
				{
					"veh_infantry_medic_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_medic_s";
		textPlural="$STR_A3_nameSound_veh_infantry_medic_p";
		nameSound="veh_infantry_medic_s";
		_generalMacro="I_P_medic_02_F";
		displayName="$STR_B_medic_F0";
		scope=2;
		scopeCurator=2;
		backpack="G_FieldPack_Medic";
		weapons[]=
		{
			"arifle_Mk20_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_Mk20_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnmagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_TacVest_blk",
			"H_HelmetIA",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_blk",
			"H_HelmetIA",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		attendant=1;
		icon="iconManMedic";
		role="CombatLifeSaver";
		picture="pictureHeal";
		model="\A3\characters_F_gamma\Guerrilla\ig_guerrilla2_1.p3d";
		uniformClass="U_IG_Guerilla2_3";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\ig_guerrilla2_3_co.paa"
		};
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_HelmetIA"
		};
		headgearList[]=
		{
			"H_HelmetIA",
			1
		};
	};
	class I_P_Soldier_01_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		_generalMacro="I_P_Soldier_01_F";
		displayName="$STR_A3_CfgVehicles_B_Soldier_F0";
		scope=2;
		scopeCurator=2;
		weapons[]=
		{
			"arifle_TRG21_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_TRG21_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnmagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_PASGT_basic_olive_F",
			"G_EyeProtectors_base_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_PASGT_basic_olive_F",
			"G_EyeProtectors_base_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\c_cloth1_kabeiroi_co.paa",
			"a3\characters_f_beta\indep\data\ia_soldier_01_clothing_co.paa"
		};
		uniformClass="U_BG_leader";
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_PASGT_basic_olive_F"
		};
		role="Rifleman";
		headgearList[]=
		{
			"H_PASGT_basic_olive_F",
			1
		};
	};
	class I_P_Soldier_02_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		_generalMacro="I_P_Soldier_02_F";
		displayName="$STR_A3_CfgVehicles_B_Soldier_F0";
		scope=2;
		scopeCurator=2;
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnmagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_PASGT_basic_olive_F",
			"G_EyeProtectors_base_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_PASGT_basic_olive_F",
			"G_EyeProtectors_base_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Bootcamp\Guerrilla\Data\c_cloth1_kabeiroi_co.paa",
			"a3\characters_f_beta\indep\data\ia_soldier_01_clothing_co.paa"
		};
		uniformClass="U_BG_leader";
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_PASGT_basic_olive_F"
		};
		role="Rifleman";
		headgearList[]=
		{
			"H_PASGT_basic_olive_F",
			1
		};
	};
	class I_P_Soldier_SL_01_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		_generalMacro="I_P_Soldier_SL_01_F";
		displayName="$STR_B_Soldier_SL_F0";
		scope=2;
		scopeCurator=2;
		cost=250000;
		camouflage=1.6;
		icon="iconManLeader";
		role="Rifleman";
		weapons[]=
		{
			"arifle_TRG20_ACO_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_TRG20_ACO_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Yellow",
			"30Rnd_556x45_Stanag_Tracer_Yellow",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag_Tracer_Yellow",
			"30Rnd_556x45_Stanag_Tracer_Yellow",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_Chestrig_blk",
			"H_PASGT_basic_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_blk",
			"H_PASGT_basic_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		model="\A3\characters_F_gamma\Guerrilla\ig_leader.p3d";
		uniformClass="U_IG_leader";
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_PASGT_basic_olive_F"
		};
		allowedHeadgearB[]=
		{
			"H_PASGT_basic_olive_F",
			"H_PASGT_basic_black_F"
		};
		headgearList[]=
		{
			"H_PASGT_basic_olive_F",
			1,
			"H_PASGT_basic_black_F",
			1
		};
	};
	class I_P_Soldier_SL_02_F: I_P_Soldier_base_F
	{
		author="O&T Expansion Eden";
		_generalMacro="I_P_Soldier_SL_02_F";
		displayName="$STR_B_Soldier_SL_F0";
		scope=2;
		scopeCurator=2;
		cost=250000;
		camouflage=1.6;
		icon="iconManLeader";
		role="Rifleman";
		weapons[]=
		{
			"srifle_DMR_06_camo_MRCO_BI_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_06_camo_MRCO_BI_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_Chestrig_blk",
			"H_PASGT_basic_black_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_blk",
			"H_PASGT_basic_black_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		model="\A3\characters_F_gamma\Guerrilla\ig_leader.p3d";
		uniformClass="U_IG_leader";
		headgearProbability=100;
		allowedHeadgear[]=
		{
			"H_PASGT_basic_black_F"
		};
		allowedHeadgearB[]=
		{
			"H_PASGT_basic_olive_F",
			"H_PASGT_basic_black_F"
		};
		headgearList[]=
		{
			"H_PASGT_basic_olive_F",
			1,
			"H_PASGT_basic_black_F",
			1
		};
	};
};
