class CfgPatches
{
	class A3_Characters_expEden_scimitarRegiment
	{
		addonRootClass="A3_expEden_characters";
		requiredAddons[]=
		{
			"A3_expEden_characters"
		};
		requiredVersion=0.1;
		units[]=
		{
			"O_A_medic_F",
			"O_A_officer_F",
			"O_A_soldier_A_F",
			"O_A_soldier_AA_F",
			"O_A_soldier_AR_F",
			"O_A_soldier_AT_F",
			"O_A_soldier_GL_F",
			"O_A_soldier_LAT_F",
			"O_A_soldier_M_F",
			"O_A_soldier_SL_F"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class O_Soldier_base_F;
	class O_officer_F: O_Soldier_base_F
	{
		class EventHandlers;
	};
	class O_A_soldier_base_F: O_officer_F
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="O_A_soldier_base_F";
		scope=1;
		model="\A3\characters_F\OPFOR\o_officer_noinsignia_f.p3d";
		modelSides[]={0,1,2,3,4,5,6,7};
		side=0;
		editorSubcategory="EdSubcat_Personnel_scimitarRegiment";
		icon="iconMan";
		role="Rifleman";
		camouflage=1.6;
		uniformClass="U_O_officer_noInsignia_hex_F";
		identityTypes[]=
		{
			"LanguageFRE_F",
			"Head_African",
			"G_IRAN_default"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\officer_noinsignia_hex_co",
			"\A3\UI_F_Tacops\Data\CfgUnitInsignia\csat_scimitarRegiment_ca.paa"
		};
		items[]=
		{
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		class Wounds
		{
			mat[]=
			{
				"A3\Characters_F\OPFOR\Data\officer_noInsignia.rvmat",
				"A3\Characters_F\OPFOR\Data\officer_injury_noinsignia.rvmat",
				"A3\Characters_F\OPFOR\Data\officer_injury_noinsignia.rvmat"
			};
			tex[]={};
		};
		class EventHandlers: EventHandlers
		{
			init="[_this # 0,'CSAT_ScimitarRegiment'] call BIS_fnc_setUnitInsignia;";
		};
		class AttributeValues
		{
			UnitInsignia="CSAT_ScimitarRegiment";
		};
	};
	class O_A_soldier_A_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_s"
				};
				speechPlural[]=
				{
					"veh_infantry_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_s";
		textPlural="$STR_A3_nameSound_veh_infantry_p";
		nameSound="veh_infantry_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_A_F.jpg";
		_generalMacro="O_A_soldier_A_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_A_F0";
		items[]=
		{
			"FirstAidKit"
		};
		respawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_CTAR_blk_flash_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_flash_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		backpack="B_FieldPack_cbr_Ammo_F";
	};
	class O_A_soldier_AR_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_MG_s"
				};
				speechPlural[]=
				{
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_AR_F.jpg";
		_generalMacro="O_A_soldier_AR_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_soldier_AR_F0";
		icon="iconManMG";
		role="MachineGunner";
		cost=220000;
		linkedItems[]=
		{
			"V_Chestrig_khk",
			"H_Cap_brn_SPECOPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_khk",
			"H_Cap_brn_SPECOPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_CTARS_blk_flash_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTARS_blk_flash_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
	};
	class O_A_medic_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_medic_s"
				};
				speechPlural[]=
				{
					"veh_infantry_medic_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_medic_s";
		textPlural="$STR_A3_nameSound_veh_infantry_medic_p";
		nameSound="veh_infantry_medic_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_medic_F.jpg";
		_generalMacro="O_A_medic_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_medic_F0";
		icon="iconManMedic";
		picture="pictureHeal";
		role="CombatLifeSaver";
		attendant=1;
		linkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_CTAR_blk_flash_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_flash_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		backpack="B_AssaultPack_ocamo_Medic_F";
	};
	class O_A_soldier_GL_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_s"
				};
				speechPlural[]=
				{
					"veh_infantry_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_s";
		textPlural="$STR_A3_nameSound_veh_infantry_p";
		nameSound="veh_infantry_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_GL_F.jpg";
		_generalMacro="O_A_soldier_GL_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_GL_F0";
		role="Grenadier";
		cost=200000;
		linkedItems[]=
		{
			"V_Chestrig_khk",
			"H_Cap_brn_SPECOPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_khk",
			"H_Cap_brn_SPECOPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_CTAR_GL_blk_arco_flash_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_GL_blk_arco_flash_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
	};
	class O_A_soldier_M_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_sniper_s"
				};
				speechPlural[]=
				{
					"veh_infantry_sniper_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
		nameSound="veh_infantry_sniper_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_M_F.jpg";
		_generalMacro="O_A_soldier_M_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_M_F0";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		linkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"srifle_DMR_07_blk_F_arco_flash_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_07_blk_F_arco_flash_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"20Rnd_650x39_Cased_Mag_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
	};
	class O_A_officer_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_officer_F.jpg";
		_generalMacro="O_A_officer_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_officer_F0";
		icon="iconManOfficer";
		cost=250000;
		linkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_Beret_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_Beret_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"SMG_02_flash_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"SMG_02_flash_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
	};
	class O_A_soldier_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		editorSubcategory="EdSubcat_Personnel_scimitarRegiment";
		scope=2;
	};
	class O_A_soldier_LAT_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_AT_s"
				};
				speechPlural[]=
				{
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_LAT_F.jpg";
		_generalMacro="O_A_soldier_LAT_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_LAT_F0";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		threat[]={0.80000001,0.80000001,0.30000001};
		secondaryAmmoCoef=0.5;
		linkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_Cap_brn_SPECOPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_Cap_brn_SPECOPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_CTAR_blk_aco_flash_F",
			"launch_RPG32_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_aco_flash_F",
			"launch_RPG32_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"RPG32_F",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"RPG32_F",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		backpack="B_FieldPack_ocamo_LAT_F";
	};
	class O_A_soldier_SL_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_s"
				};
				speechPlural[]=
				{
					"veh_infantry_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_s";
		textPlural="$STR_A3_nameSound_veh_infantry_p";
		nameSound="veh_infantry_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_SL_F.jpg";
		_generalMacro="O_A_soldier_SL_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_SL_F0";
		icon="iconManLeader";
		cost=250000;
		linkedItems[]=
		{
			"V_Chestrig_khk",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_khk",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_CTAR_blk_arco_flash_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_arco_flash_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
	};
	class O_A_soldier_TL_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		editorSubcategory="EdSubcat_Personnel_scimitarRegiment";
		scope=2;
	};
	class O_A_soldier_AA_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_AT_s"
				};
				speechPlural[]=
				{
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_AA_F.jpg";
		_generalMacro="O_A_soldier_AA_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_AA_F0";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		threat[]={0.80000001,0.1,1};
		secondaryAmmoCoef=0.5;
		linkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_Cap_brn_SPECOPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_Cap_brn_SPECOPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_CTAR_blk_flash_F",
			"launch_O_Titan_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_flash_F",
			"launch_O_Titan_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"Titan_AA",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"Titan_AA",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		backpack="B_TacticalPack_ocamo_AA_F";
	};
	class O_A_soldier_AT_F: O_A_soldier_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_AT_s"
				};
				speechPlural[]=
				{
					"veh_infantry_AT_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\O_A_soldier_AT_F.jpg";
		_generalMacro="O_A_soldier_AT_F";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_AT_F0";
		icon="iconManAT";
		role="MissileSpecialist";
		cost=130000;
		threat[]={0.80000001,0.80000001,0.30000001};
		secondaryAmmoCoef=0.5;
		linkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_MilCap_ocamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_CTAR_blk_flash_F",
			"launch_O_Titan_short_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_flash_F",
			"launch_O_Titan_short_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"Titan_AT",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"Titan_AT",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		backpack="B_TacticalPack_ocamo_AT_F";
	};
};
