class CfgPatches
{
	class Props_Globe_Humanitarian_Garbage
	{
		addonRootClass="A3_Props_F_Globe";
		requiredAddons[]=
		{
			"Props_Globe_Humanitarian"
		};
		requiredVersion=0.1;
		units[]=
		{
			"GarbageElectronics_01",
			"GarbageTimber_01",
			"GarbageTimber_02",
			"GarbageBrick_01",
			"GarbageBrick_01_broken",
			"GarbageRoofTiles_01",
			"BloodTrail_02_Small_New",
			"BloodTrail_02_Small_Old",
			"BloodTrail_02_Medium_New",
			"BloodTrail_02_Medium_New_help",
			"BloodTrail_Dirt_01",
			"BloodTrail_Dirt_02",
			"BloodTrail_Dirt_03",
			"BloodTrail_Dirt_04",
			"BloodSpray_02_Small_New",
			"BloodSpray_02_Small_New_bunch",
			"BloodSpray_02_Small_New_couple"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class Garbage_base_F;
	class Items_base_F;
	class Blood_01_Base_F;
	class BloodTrail_02_Small_New: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodTrail_02_Small_New.jpg";
		_generalMacro="BloodTrail_02_Small_New";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodTrail_02_Small_New0";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodTrail_02_Small_New.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_2_CA.paa"
		};
	};
	class BloodTrail_02_Small_Old: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodTrail_02_Small_Old.jpg";
		_generalMacro="BloodTrail_02_Small_Old";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodTrail_02_Small_Old0";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodTrail_02_Small_Old.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_5_CA.paa"
		};
	};
	class BloodTrail_02_Medium_New: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodTrail_02_Medium_New.jpg";
		_generalMacro="BloodTrail_02_Medium_New";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodTrail_02_Medium_New0";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodTrail_02_Medium_New.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_3_CA.paa"
		};
	};
	class BloodTrail_02_Medium_New_help: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodTrail_02_Medium_New_help.jpg";
		_generalMacro="BloodTrail_02_Medium_New_help";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodTrail_02_Medium_New_help0";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodTrail_02_Medium_New_help.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_3_CA.paa"
		};
	};
	class BloodTrail_Dirt_01: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodTrail_Dirt_01.jpg";
		_generalMacro="BloodTrail_Dirt_01";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodTrail_Dirt_010";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodTrail_Dirt_01.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_2_CA.paa"
		};
	};
	class BloodTrail_Dirt_02: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodTrail_Dirt_02.jpg";
		_generalMacro="BloodTrail_Dirt_02";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodTrail_Dirt_020";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodTrail_Dirt_02.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_2_CA.paa"
		};
	};
	class BloodTrail_Dirt_03: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodTrail_Dirt_03.jpg";
		_generalMacro="BloodTrail_Dirt_03";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodTrail_Dirt_030";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodTrail_Dirt_03.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_4_CA.paa"
		};
	};
	class BloodTrail_Dirt_04: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodTrail_Dirt_04.jpg";
		_generalMacro="BloodTrail_Dirt_04";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodTrail_Dirt_040";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodTrail_Dirt_04.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_4_CA.paa"
		};
	};
	class BloodSpray_02_Small_New: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodSpray_02_Small_New.jpg";
		_generalMacro="BloodSpray_02_Small_New";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodSpray_02_Small_New0";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodSpray_02_Small_New.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_2_CA.paa"
		};
	};
	class BloodSpray_02_Small_New_bunch: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodSpray_02_Small_New_bunch.jpg";
		_generalMacro="BloodSpray_02_Small_New_bunch";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodSpray_02_Small_New_bunch0";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodSpray_02_Small_New_bunch.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_4_CA.paa"
		};
	};
	class BloodSpray_02_Small_New_couple: Blood_01_Base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\BloodSpray_02_Small_New_couple.jpg";
		_generalMacro="BloodSpray_02_Small_New_couple";
		scope=2;
		scopeCurator=2;
		DLC="Enoch";
		displayName="$STR_Globe_CfgVehicles_BloodSpray_02_Small_New_couple0";
		model="\a3\props_f_globe\Humanitarian\Garbage\BloodSpray_02_Small_New_couple.p3d";
		hiddenSelections[]=
		{
			"camo_1"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\structures_f_enoch\data\Alpha\decal_patch_floor_3_CA.paa"
		};
	};
	class Flesh_01: Items_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		class SimpleObject
		{
			eden=1;
			animate[]={};
			hide[]={};
			verticalOffset=0.0049999999;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\Flesh_01.jpg";
		_generalMacro="Flesh_01";
		scope=2;
		scopeCurator=2;
		icon="iconObject_elipse_H";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Medicine";
		vehicleClass="Small_items";
		displayName="$STR_Globe_CfgVehicles_Flesh_010";
		model="\a3\data_f\ParticleEffects\Universal\Meat_ca.p3d";
	};
	class GarbageRoofTiles_01: Garbage_base_F
	{
		author="$STR_A3_Bohemia_Interactive";
		mapSize=2.1800003;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.45300001;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\GarbageRoofTiles_01.jpg";
		_generalMacro="GarbageRoofTiles_01";
		scope=2;
		scopeCurator=2;
		displayName="$STR_Globe_CfgVehicles_GarbageRoofTiles_010";
		model="\A3\Plants_F\Clutter\c_Rubble_Clutter1.p3d";
		icon="iconObject_1x1";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Garbage";
		vehicleClass="Garbage";
		destrType="DestructNo";
	};
	class GarbageElectronics_01: GarbageRoofTiles_01
	{
		author="$STR_A3_Bohemia_Interactive";
		mapSize=1.9903302;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.01300001;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\GarbageElectronics_01.jpg";
		_generalMacro="GarbageElectronics_01";
		displayName="$STR_Globe_CfgVehicles_GarbageElectronics_010";
		model="\A3\Plants_F\Clutter\c_Rubble_Clutter2.p3d";
		icon="iconObject_1x4";
	};
	class GarbageTimber_01: GarbageRoofTiles_01
	{
		author="$STR_A3_Bohemia_Interactive";
		mapSize=3.9903302;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.19330001;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\GarbageTimber_01.jpg";
		_generalMacro="GarbageTimber_01";
		displayName="$STR_Globe_CfgVehicles_GarbageTimber_010";
		model="\A3\Plants_F\Clutter\c_Rubble_Clutter3.p3d";
		icon="iconObject_1x1";
	};
	class GarbageTimber_02: GarbageTimber_01
	{
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\GarbageTimber_02.jpg";
		_generalMacro="GarbageTimber_02";
		displayName="$STR_Globe_CfgVehicles_GarbageTimber_020";
		model="\A3\Plants_F\Clutter\c_Rubble_Clutter4.p3d";
	};
	class GarbageBrick_01: GarbageRoofTiles_01
	{
		author="$STR_A3_Bohemia_Interactive";
		mapSize=2.2203112;
		class SimpleObject
		{
			eden=0;
			animate[]={};
			hide[]={};
			verticalOffset=0.01130001;
			verticalOffsetWorld=0;
			init="''";
		};
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\GarbageBrick_01.jpg";
		_generalMacro="GarbageBrick_01";
		displayName="$STR_Globe_CfgVehicles_GarbageBrick_010";
		model="\A3\Plants_F\Clutter\c_Rubble_Clutter6.p3d";
		icon="iconObject_1x1";
	};
	class GarbageBrick_01_broken: GarbageBrick_01
	{
		editorPreview="\A3\EditorPreviews_F_expEden\Data\CfgVehicles\GarbageBrick_01_broken.jpg";
		_generalMacro="GarbageBrick_01_broken";
		displayName="$STR_Globe_CfgVehicles_GarbageBrick_01_broken0";
		model="\A3\Plants_F\Clutter\c_Rubble_Clutter5.p3d";
		icon="iconObject_1x2";
	};
};
